# -*- coding: utf-8 -*-
"""drone_collector/browser.py -- drive SmartFarm in a real browser and capture
the flight-list responses it fetches for itself.

Why a browser at all. DJI signs every API request with a `Signature` header
generated by its own bundled WASM. Tested against the live site on 2026-07-31:
dropping the header returns body `code 101`, and rewriting `page_size=30` to
`page_size=100` on an otherwise genuine request also returns `code 101`. So the
requests are issued by the site, and we only listen. Three consequences run
through this whole module:

  * page_size is 30 and cannot be changed;
  * the reporting period cannot be put into the URL -- it is set through the
    site's own date picker and then VERIFIED against the URL the site produced;
  * pagination is by page number, through the site's own control.

Do not try to generate, replay or reverse-engineer the Signature header. It
has been tested and it does not work.

Success is NOT the HTTP status. Every response is HTTP 200; success or failure
is the `code` field inside the JSON body: 200 means data, 101 and 408 mean
rejection. Any code path that decides success from response.status is wrong.

Selectors. The site cannot be reached from the development machine, so every
selector below is a module-level constant with a comment: when one turns out
to be wrong on the live cabinet it is corrected here, in one place, and
nowhere else.
"""

import logging
import time

from datetime import datetime, timedelta

from urllib.parse import parse_qs, urlsplit

log = logging.getLogger(__name__)


# ─── The API we listen to ─────────────────────────────────────────────────────

# The flight LIST call. The trailing '?' is part of the marker: it is what
# separates the list endpoint from a flight detail URL.
FLIGHT_LIST_URL_MARKER = '/api/web/v1/flight_records?'

# Detail URLs look like /api/web/v1/flight_records/574320663 and must never be
# captured -- their body has no `data` list and no meta_data.
FLIGHT_DETAIL_URL_MARKER = '/flight_records/'

# In-body status. NOT the HTTP status: every response is HTTP 200.
BODY_CODE_OK = 200

# Query parameters carrying the period, as the site itself spells them. They
# arrive percent-encoded (filters%5Btimestamp_gteq%5D); parse_qs decodes both
# keys and values, so the decoded spelling is what we match on.
PARAM_PERIOD_FROM = 'filters[timestamp_gteq]'
PARAM_PERIOD_TO = 'filters[timestamp_lteq]'


# ─── Selectors (correct these here, nowhere else) ─────────────────────────────

# Ant Design range picker: one wrapper holding two <input> elements.
SELECTOR_RANGE_PICKER = '.ant-picker-range'

# The two date inputs. In Ant Design markup the wrapper is a
# <div class="ant-picker-input"> holding the <input>, so the working selector
# is `.ant-picker-input input` -- not `input.ant-picker-input input`, which
# would mean an input inside an input and matches nothing.
SELECTOR_RANGE_INPUTS = '.ant-picker-range .ant-picker-input input'

# Fallback when the wrapper class differs: the two plain <input> descendants
# of the picker, in document order.
SELECTOR_RANGE_INPUTS_FALLBACK = '.ant-picker-range input'

# Ant Design pagination. The [aria-disabled='false'] form is used for clicking
# so a disabled control is simply not found; the bare form is used to ask
# whether the control exists at all.
SELECTOR_PAGINATION_NEXT = 'li.ant-pagination-next'
SELECTOR_PAGINATION_NEXT_ENABLED = "li.ant-pagination-next[aria-disabled='false']"

# Cookie-consent banner. It overlays the bottom of the page and swallows
# clicks on the pagination control.
SELECTOR_COOKIE_ACCEPT = ("button.cc-consent-accept, "
                          "button:has-text('Accept All Cookies'), "
                          "button:has-text('Accept')")

# The records page opens in map mode by default, and map mode only fetches
# /flight_records/overview -- no list, no capture. DJI_RECORDS_URL points at
# /records/list so this is normally unnecessary; it is attempted only when
# nothing was captured after the initial load.
SELECTOR_LIST_VIEW = ("button:has-text('List'), "
                      "[role='tab']:has-text('List'), "
                      "span:has-text('List')")

NAVIGATION_WAIT_UNTIL = 'domcontentloaded'

# How long to wait for the site to fetch its first flight list after a
# navigation, in milliseconds. Generous: the previous collector's failures
# were overwhelmingly slow XHRs, not missing ones.
FIRST_CAPTURE_TIMEOUT_MS = 60000

# Polling granularity while waiting for a capture.
CAPTURE_POLL_MS = 250


# The site rounds the period it was given (and may apply its own idea of the
# day's edges), so the returned URL is compared against the intended bounds
# with one hour of slack on each edge. One hour absorbs rounding; it is far
# too small to hide the failure this check exists for -- a period the picker
# ignored, or a range the calendar reset because it crossed a year boundary,
# is wrong by a day or more.
PERIOD_TOLERANCE_MS = 3600 * 1000

# Delay between keystrokes when typing into the date inputs. Ant Design
# revalidates on every keystroke; typing instantly has been known to leave the
# control holding a partial date.
KEY_DELAY_MS = 40


class BrowserError(Exception):
    """The browser side of the run failed."""


class SessionExpired(BrowserError):
    """The saved session no longer signs us in. main() -> exit code 2."""


class PeriodVerificationFailed(BrowserError):
    """The site is not showing the period we asked for. main() -> exit code 3.

    [REASON]: a collector that silently harvests the wrong period is worse
    than one that fails -- the flights it brings back are real, they land in
    the database, and nothing downstream can tell that the window was not the
    one the operator asked for. So this is fatal and nothing is sent.
    """


# ─── Pure response filtering (unit-tested, no browser) ────────────────────────

def is_flight_list_url(url):
    """True for the flight LIST endpoint, False for detail URLs and the rest.

    Both conditions of the task are applied: the URL must contain
    '/api/web/v1/flight_records?' and must NOT contain '/flight_records/'.
    """
    if not url:
        return False
    if FLIGHT_LIST_URL_MARKER not in url:
        return False
    if FLIGHT_DETAIL_URL_MARKER in url:
        return False
    return True


def body_code(body):
    """The in-body `code`, or None when the body is not a usable object."""
    if not isinstance(body, dict):
        return None
    value = body.get('code')
    if isinstance(value, bool):
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def is_flight_list_body(body):
    """True when the body carries data: code == 200 AND a `data` list."""
    return body_code(body) == BODY_CODE_OK and isinstance(body.get('data'), list)


def classify_response(url, body):
    """(accepted, reason) for one response.

    Reasons are stable strings, so the run summary can count them:
      'ok'                 -- captured
      'not-flight-list'    -- some other endpoint, ignored entirely
      'detail-url'         -- a single flight card, excluded by contract
      'code-101' / 'code-408' / 'code-none' -- the server rejected the request
      'no-data-list'       -- code 200 but no `data` list: not usable
    """
    if url and FLIGHT_DETAIL_URL_MARKER in url and 'flight_records' in url:
        return False, 'detail-url'
    if not is_flight_list_url(url):
        return False, 'not-flight-list'
    code = body_code(body)
    if code != BODY_CODE_OK:
        return False, 'code-%s' % ('none' if code is None else code)
    if not isinstance(body.get('data'), list):
        return False, 'no-data-list'
    return True, 'ok'


class CapturedPage(object):
    """One accepted flight-list response: the body plus the URL that asked."""

    __slots__ = ('url', 'body')

    def __init__(self, url, body):
        self.url = url
        self.body = body

    @property
    def meta(self):
        meta = self.body.get('meta_data')
        return meta if isinstance(meta, dict) else {}

    @property
    def current_page(self):
        return _as_int(self.meta.get('current_page'))

    @property
    def total_pages(self):
        return _as_int(self.meta.get('total_pages'))

    @property
    def flights(self):
        data = self.body.get('data')
        return [row for row in data if isinstance(row, dict)] if data else []

    def __repr__(self):
        return ('CapturedPage(page=%s/%s, flights=%d)'
                % (self.current_page, self.total_pages, len(self.flights)))


def _as_int(value):
    if value is None or isinstance(value, bool):
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


# ─── Period verification (unit-tested, no browser) ────────────────────────────

def parse_period_from_url(url):
    """(from_ms, to_ms) read out of a flight-list request URL.

    The parameters arrive percent-encoded as filters%5Btimestamp_gteq%5D;
    parse_qs decodes keys as well as values, so both spellings land on the
    same key. A parameter that is absent or not an integer comes back None.
    """
    if not url:
        return (None, None)
    params = parse_qs(urlsplit(url).query, keep_blank_values=True)
    return (_first_int(params.get(PARAM_PERIOD_FROM)),
            _first_int(params.get(PARAM_PERIOD_TO)))


def _first_int(values):
    if not values:
        return None
    return _as_int(values[0])


def period_matches(url, expected_from_ms, expected_to_ms,
                   tolerance_ms=PERIOD_TOLERANCE_MS):
    """True when the URL's period matches the intended one within tolerance.

    A URL carrying neither bound never matches: "no filter parameters" means
    the picker was not applied at all, which is exactly the failure this
    function exists to catch.
    """
    observed_from, observed_to = parse_period_from_url(url)
    if observed_from is None or observed_to is None:
        return False
    return (abs(observed_from - expected_from_ms) <= tolerance_ms
            and abs(observed_to - expected_to_ms) <= tolerance_ms)


def format_ms(value, tz_offset_hours):
    """'1782846000000 (2026-07-01 00:00:00 +5)' -- for log lines and errors.

    Both the raw number and its local rendering are shown: the number is what
    the site sent, the rendering is what a human can compare against the
    period they asked for.
    """
    if value is None:
        return 'absent'
    moment = (datetime(1970, 1, 1)
              + timedelta(milliseconds=value)
              + timedelta(hours=tz_offset_hours))
    sign = '+' if tz_offset_hours >= 0 else '-'
    return '%d (%s %s%g)' % (value, moment.strftime('%Y-%m-%d %H:%M:%S'),
                             sign, abs(tz_offset_hours))


# ─── The driver ───────────────────────────────────────────────────────────────

class FlightCollector(object):
    """Opens SmartFarm with a saved session and captures its flight lists.

    Usage:

        with FlightCollector(cfg) as collector:
            collector.open_records()
            ...

    Every captured page is kept with the URL that produced it, because the
    period verification reads the period back out of that URL.
    """

    def __init__(self, cfg, logger=None):
        self.cfg = cfg
        self.log = logger or log
        self._playwright = None
        self._browser = None
        self._context = None
        self._page = None
        self._captured = []
        self._rejected = {}
        self._ignored_detail = 0

    # -- lifecycle ------------------------------------------------------------

    def __enter__(self):
        self.start()
        return self

    def __exit__(self, *_exc):
        self.close()

    def start(self):
        """Launch Chromium with the saved session and attach the listener.

        [REASON]: the listener is attached BEFORE the first navigation. The
        site fetches its first flight list during page load; a listener
        attached after goto() misses it, and the run then either waits out its
        timeout or -- worse -- verifies the period against a URL that came
        from a later, different request.
        """
        # Lazy import: the collector's dependencies are not installed in the
        # application's Python, where the unit tests and CI import this module.
        from playwright.sync_api import sync_playwright

        from drone_collector.session import require_session

        state = require_session(self.cfg.storage_state)

        self._playwright = sync_playwright().start()
        self._browser = self._playwright.chromium.launch(
            headless=self.cfg.headless)
        self._context = self._browser.new_context(
            storage_state=str(state),
            locale='en-US',
        )
        self._page = self._context.new_page()
        self._page.set_default_timeout(self.cfg.page_timeout_ms)
        self._page.on('response', self._on_response)
        return self

    def close(self):
        for closer in (self._context, self._browser):
            try:
                if closer is not None:
                    closer.close()
            except Exception:  # pragma: no cover -- teardown must not mask errors
                pass
        try:
            if self._playwright is not None:
                self._playwright.stop()
        except Exception:  # pragma: no cover
            pass
        self._context = self._browser = self._playwright = self._page = None

    # -- capture --------------------------------------------------------------

    def _on_response(self, response):
        """Response listener. Never raises: an exception here would surface
        inside Playwright's event loop and abort the navigation."""
        try:
            url = response.url
        except Exception:  # pragma: no cover
            return
        if url and FLIGHT_DETAIL_URL_MARKER in url and 'flight_records' in url:
            self._ignored_detail += 1
            return
        if not is_flight_list_url(url):
            return
        try:
            body = response.json()
        except Exception:
            self._note_rejected('unparsable-body', url)
            return
        # [REASON]: the decision is made on the in-body `code`, never on
        # response.status -- the server answers HTTP 200 for rejections too,
        # so a status check would accept `code 101` as data.
        accepted, reason = classify_response(url, body)
        if not accepted:
            self._note_rejected(reason, url)
            return
        page = CapturedPage(url, body)
        self._captured.append(page)
        self.log.info('Captured page %s/%s (%d flights)',
                      page.current_page, page.total_pages, len(page.flights))

    def _note_rejected(self, reason, url):
        self._rejected[reason] = self._rejected.get(reason, 0) + 1
        # The URL carries only filter parameters -- no token, no cookie, no
        # header. It is logged because the period is read out of it.
        self.log.warning('Rejected flight-list response (%s): %s', reason, url)

    @property
    def captured(self):
        return list(self._captured)

    @property
    def rejected(self):
        return dict(self._rejected)

    @property
    def ignored_detail_responses(self):
        return self._ignored_detail

    def _wait_for_capture(self, previous_count, timeout_ms):
        """Block until len(self._captured) exceeds previous_count.

        Returns True when a new page arrived. Uses the page's own wait so that
        Playwright keeps pumping its event loop -- a plain time.sleep() would
        stop the listener from ever running.
        """
        deadline = time.time() + (timeout_ms / 1000.0)
        while time.time() < deadline:
            if len(self._captured) > previous_count:
                return True
            self._page.wait_for_timeout(CAPTURE_POLL_MS)
        return len(self._captured) > previous_count

    # -- navigation -----------------------------------------------------------

    def open_records(self):
        """Navigate to the records page and wait for its first flight list."""
        self.log.info('Opening %s', self.cfg.records_url)
        self._page.goto(self.cfg.records_url,
                        wait_until=NAVIGATION_WAIT_UNTIL,
                        timeout=self.cfg.page_timeout_ms)
        self.log.info('Page URL after navigation: %s', self._page.url)

        if '/login' in (self._page.url or ''):
            raise SessionExpired(
                'the saved session at %s is no longer signed in (landed on '
                '%s) -- run `python -m drone_collector.main --save-session` '
                'again' % (self.cfg.storage_state, self._page.url))

        self.dismiss_cookie_banner()

        if not self._wait_for_capture(0, FIRST_CAPTURE_TIMEOUT_MS):
            # Map mode only fetches /flight_records/overview. One best-effort
            # attempt at the list toggle before giving up.
            self.log.warning('No flight list after %d ms, trying the List view'
                             ' toggle', FIRST_CAPTURE_TIMEOUT_MS)
            self.switch_to_list_view()
            self._wait_for_capture(0, FIRST_CAPTURE_TIMEOUT_MS)

        if not self._captured:
            if '/login' in (self._page.url or ''):
                raise SessionExpired(
                    'the saved session at %s expired during the run'
                    % self.cfg.storage_state)
            raise BrowserError(
                'the site fetched no flight list within %d ms (rejected: %s, '
                'final URL: %s)' % (FIRST_CAPTURE_TIMEOUT_MS,
                                    self._rejected or 'none', self._page.url))
        return self._captured[0]

    def dismiss_cookie_banner(self):
        """Best-effort: the banner overlays the pagination control."""
        try:
            button = self._page.locator(SELECTOR_COOKIE_ACCEPT).first
            if button.is_visible(timeout=3000):
                button.click()
                self._page.wait_for_timeout(500)
                self.log.info('Cookie banner dismissed')
        except Exception as exc:
            self.log.info('No cookie banner to dismiss (%s)', exc)

    def switch_to_list_view(self):
        """Best-effort: map mode never fetches the flight list."""
        try:
            toggle = self._page.locator(SELECTOR_LIST_VIEW).first
            toggle.click(timeout=10000)
            self._page.wait_for_timeout(self.cfg.settle_ms)
            self.log.info('Switched to the List view')
        except Exception as exc:
            self.log.info('List view toggle not used (%s)', exc)

    # -- period ---------------------------------------------------------------

    def _range_inputs(self):
        """The two date inputs of the Ant Design range picker, in order."""
        for selector in (SELECTOR_RANGE_INPUTS, SELECTOR_RANGE_INPUTS_FALLBACK):
            locator = self._page.locator(selector)
            try:
                count = locator.count()
            except Exception:
                count = 0
            if count >= 2:
                self.log.info('Range picker inputs found with %r', selector)
                return [locator.nth(0), locator.nth(1)]
        raise BrowserError(
            'the date range picker was not found -- looked for %r and %r under '
            '%r. Correct the selector constants at the top of browser.py.'
            % (SELECTOR_RANGE_INPUTS, SELECTOR_RANGE_INPUTS_FALLBACK,
               SELECTOR_RANGE_PICKER))

    def _type_date(self, field, text):
        """Click, select all, type YYYY-MM-DD, press Enter."""
        field.click(timeout=self.cfg.page_timeout_ms)
        # Select whatever the control already holds; Ant Design keeps the
        # previous value in the input and typing would otherwise append to it.
        field.press('Control+a')
        # press_sequentially replaced type() in newer Playwright; both are
        # tried so the collector is not pinned to one minor version.
        try:
            field.press_sequentially(text, delay=KEY_DELAY_MS)
        except AttributeError:  # pragma: no cover -- older Playwright
            field.type(text, delay=KEY_DELAY_MS)
        field.press('Enter')
        self._page.wait_for_timeout(self.cfg.settle_ms)

    def set_period(self, date_from, date_to):
        """Type the period into the picker, then prove the site accepted it.

        The period cannot be put into the request URL: an altered query string
        fails DJI's signature check (`code 101`). It has to go through the
        site's own control, which is why it then has to be verified rather
        than assumed.

        Returns (from_ms, to_ms) -- the intended bounds, once verified.
        """
        from drone_collector.window import format_date, window_bounds_ms

        expected_from, expected_to = window_bounds_ms(
            date_from, date_to, self.cfg.tz_offset_hours)

        fields = self._range_inputs()

        # [REASON]: everything captured so far belongs to the site's DEFAULT
        # period, not to ours. Keeping it would mix flights from an unasked-for
        # window into the batch, and the run summary would still look right.
        discarded = len(self._captured)
        self._captured = []
        if discarded:
            self.log.info('Discarded %d page(s) captured before the period was '
                          'set', discarded)

        self.log.info('Setting period %s .. %s', format_date(date_from),
                      format_date(date_to))
        self._type_date(fields[0], format_date(date_from))
        self._type_date(fields[1], format_date(date_to))

        if not self._captured:
            self._wait_for_capture(0, FIRST_CAPTURE_TIMEOUT_MS)

        self.verify_period(expected_from, expected_to)
        return expected_from, expected_to

    def verify_period(self, expected_from_ms, expected_to_ms):
        """Read the period back out of the site's own request URL.

        Mandatory, and fatal when it fails: the intended and the observed
        values are both logged, PeriodVerificationFailed is raised, and the
        run sends nothing.
        """
        tz = self.cfg.tz_offset_hours
        intended = 'intended %s .. %s' % (format_ms(expected_from_ms, tz),
                                          format_ms(expected_to_ms, tz))
        if not self._captured:
            raise PeriodVerificationFailed(
                'no flight-list request was captured after the period was set '
                '(%s); rejected responses: %s'
                % (intended, self._rejected or 'none'))

        url = self._captured[-1].url
        observed_from, observed_to = parse_period_from_url(url)
        observed = 'observed %s .. %s' % (format_ms(observed_from, tz),
                                          format_ms(observed_to, tz))

        if not period_matches(url, expected_from_ms, expected_to_ms):
            self.log.error('Period verification failed: %s; %s', intended,
                           observed)
            self.log.error('Observed request URL: %s', url)
            raise PeriodVerificationFailed(
                'the site is showing a different period: %s; %s' % (intended,
                                                                    observed))

        self.log.info('Period verified: %s; %s', intended, observed)
        self._drop_captures_outside_period(expected_from_ms, expected_to_ms)
        return True

    def _drop_captures_outside_period(self, expected_from_ms, expected_to_ms):
        """Keep only pages whose own URL carries the verified period.

        [REASON]: the picker fires a request after the START date is entered,
        while the end date is still the old one. That intermediate page is a
        real, well-formed flight list for a period nobody asked for. The last
        captured URL is the one verified above; the rest are filtered here so
        that a half-applied period cannot contribute flights to the batch.
        """
        kept, dropped = [], 0
        for page in self._captured:
            if period_matches(page.url, expected_from_ms, expected_to_ms):
                kept.append(page)
            else:
                dropped += 1
        if dropped:
            self.log.info('Dropped %d page(s) captured with a half-applied '
                          'period', dropped)
        self._captured = kept
        return dropped
