# -*- coding: utf-8 -*-
"""drone_collector/browser.py -- drive SmartFarm in a real browser and capture
the flight-list responses it fetches for itself.

Why a browser at all. DJI signs every API request with a `Signature` header
generated by its own bundled WASM. Tested against the live site on 2026-07-31:
dropping the header returns body `code 101`, and rewriting `page_size=30` to
`page_size=100` on an otherwise genuine request also returns `code 101`. So the
requests are issued by the site, and we only listen. Three consequences run
through this whole module:

  * nothing in a URL may be edited after the site has signed it;
  * the reporting period cannot be put into the URL -- it is set through the
    site's own date picker and then VERIFIED against the URL the site produced;
  * pagination is by page number, through the site's own control.

Note what the signature test does NOT prove. It proves that an ALTERED URL is
rejected, not that the values in it are fixed. page_size in particular is a
per-session setting with its own control on the page: when that control is
used, the app signs a request carrying the new value. It has been observed at
30 in one session and 50 in another. maximise_page_size() therefore drives
that control -- and only that control.

Do not try to generate, replay or reverse-engineer the Signature header. It
has been tested and it does not work.

serial_number is NOT a machine identifier. It is unique per flight (verified
on 10 385 records), so it is a second flight id. Nothing here keys, groups or
deduplicates on it; deduplication is on `id` alone.

Success is NOT the HTTP status. Every response is HTTP 200; success or failure
is the `code` field inside the JSON body: 200 means data, 101 and 408 mean
rejection. Any code path that decides success from response.status is wrong.

Selectors. The site cannot be reached from the development machine, so every
selector below is a module-level constant with a comment: when one turns out
to be wrong on the live cabinet it is corrected here, in one place, and
nowhere else.
"""

import logging
import re
import time

from datetime import datetime, timedelta

from urllib.parse import parse_qs, urlsplit

log = logging.getLogger(__name__)


# ─── The API we listen to ─────────────────────────────────────────────────────

# The flight LIST call. The trailing '?' is part of the marker: it is what
# separates the list endpoint from a flight detail URL.
FLIGHT_LIST_URL_MARKER = '/api/web/v1/flight_records?'

# [REASON]: matching is done on the endpoint name, not on the API version, so
# that a version bump on DJI's side does not turn every run into a silent
# "0 flights collected". A URL that matches this but not the full marker above
# is captured AND logged as an API-version change, so the constant can be
# corrected deliberately instead of being discovered by an empty database.
# It is still specific: the same page also fetches /aggr? and /aggr_by_day?
# with the very same filter parameters, and neither matches this.
FLIGHT_LIST_URL_MARKER_LOOSE = '/flight_records?'

# Detail URLs look like /api/web/v1/flight_records/574320663 and must never be
# captured -- their body has no `data` list and no meta_data.
FLIGHT_DETAIL_URL_MARKER = '/flight_records/'

# In-body status. NOT the HTTP status: every response is HTTP 200.
BODY_CODE_OK = 200

# Query parameters carrying the period, as the site itself spells them. They
# arrive percent-encoded (filters%5Btimestamp_gteq%5D); parse_qs decodes both
# keys and values, so the decoded spelling is what we match on.
PARAM_PERIOD_FROM = 'filters[timestamp_gteq]'
PARAM_PERIOD_TO = 'filters[timestamp_lteq]'


# ─── Selectors (correct these here, nowhere else) ─────────────────────────────
#
# Verified on 2026-07-31 against a saved DOM of the live /records/list page.
# The markup found there, trimmed to what matters:
#
#   <div class="ant-picker ant-picker-range ant-picker-middle">
#     <div class="ant-picker-input ant-picker-input-active">
#       <input readonly placeholder="Start date" value="2026-01-01">
#     <div class="ant-picker-range-separator">...
#     <div class="ant-picker-input">
#       <input readonly placeholder="End date" value="2026-07-31">
#
#   <ul class="ant-pagination ant-pagination-mini">
#     <li title="Previous Page" class="ant-pagination-prev ant-pagination-disabled"
#         aria-disabled="true">
#     <li title="Next Page" class="ant-pagination-next" aria-disabled="false">
#
# What that confirms: the value format is YYYY-MM-DD, which is what is typed;
# the two inputs sit in .ant-picker-input wrappers in document order; the
# pagination controls are <li> elements whose disabled state is carried by
# aria-disabled, exactly as matched below.

# Ant Design range picker: one wrapper holding two <input> elements.
SELECTOR_RANGE_PICKER = '.ant-picker-range'

# The two date inputs. The wrapper is a <div class="ant-picker-input"> holding
# the <input>, so the working selector is `.ant-picker-input input` -- not
# `input.ant-picker-input input`, which would mean an input inside an input
# and matches nothing.
SELECTOR_RANGE_INPUTS = '.ant-picker-range .ant-picker-input input'

# Fallback when the wrapper class differs: the two plain <input> descendants
# of the picker, in document order. Verified to yield exactly two.
SELECTOR_RANGE_INPUTS_FALLBACK = '.ant-picker-range input'

# Placeholders on those two inputs, kept as a documented last resort if
# document order ever stops being reliable: 'Start date' and 'End date'.
SELECTOR_RANGE_INPUT_START = '.ant-picker-range input[placeholder="Start date"]'
SELECTOR_RANGE_INPUT_END = '.ant-picker-range input[placeholder="End date"]'

# Ant Design pagination. The [aria-disabled='false'] form is used for clicking
# so a disabled control is simply not found; the bare form is used to ask
# whether the control exists at all. Confirmed against the dump: the disabled
# control carries aria-disabled="true" and the class ant-pagination-disabled.
SELECTOR_PAGINATION_NEXT = 'li.ant-pagination-next'
SELECTOR_PAGINATION_NEXT_ENABLED = "li.ant-pagination-next[aria-disabled='false']"

# Page-size control. Confirmed in the dump:
#   <div class="ant-select ... ant-pagination-options-size-changer"
#        aria-label="Page Size">
#     <div class="ant-select-selector">
#       <span class="ant-select-selection-item" title="30 / page">30 / page</span>
SELECTOR_PAGE_SIZE_CHANGER = '.ant-pagination-options-size-changer'
SELECTOR_PAGE_SIZE_CURRENT = ('.ant-pagination-options-size-changer '
                              '.ant-select-selection-item')

# The option list is NOT in the DOM until the control is opened -- Ant Design
# renders the dropdown into a portal on the body, so these are document-wide
# and cannot be scoped to the pagination element. The :not(...-hidden) part
# skips a dropdown that has been opened and closed again and is still in the
# DOM. Unverified: the saved page had never had this control opened.
SELECTOR_PAGE_SIZE_OPTIONS = ('.ant-select-dropdown:not(.ant-select-dropdown-hidden) '
                              '.ant-select-item-option')
SELECTOR_PAGE_SIZE_OPTIONS_FALLBACK = '.ant-select-item-option'

# Region indicator, for the region readback guard.
#
# [REASON]: the saved DOM of 2026-07-31 contains NO region indicator. The only
# region-ish text on the page is the sidebar navigation item "Other Regions",
# which is a switcher, not a display of the current region, and its class is a
# build-hashed CSS-module name (_menu-item-content-name_1n58w_309) that changes
# on every deploy. That item is deliberately NOT matched here: a selector that
# picked it up would compare the expected region against the string "Other
# Regions", mismatch, and block every single run -- a guard that fails closed
# on a false reading is worse than no guard.
#
# So these are candidates for an element nobody has identified yet, and the
# expected outcome today is "not found" -> a warning and a continue. The guard
# that actually protects the run is the empty-window check, which needs no
# selector at all. Correct this constant once someone finds the real element
# on the live page.
SELECTOR_REGION_INDICATOR = ('[data-testid*="region"], '
                             '[class*="current-region"], '
                             '[class*="region-name"], '
                             '[class*="regionName"]')

# Cookie-consent banner. It overlays the bottom of the page and swallows
# clicks on the pagination control.
SELECTOR_COOKIE_ACCEPT = ("button.cc-consent-accept, "
                          "button:has-text('Accept All Cookies'), "
                          "button:has-text('Accept')")

# The records page opens in map mode by default, and map mode only fetches
# /flight_records/overview -- no list, no capture. DJI_RECORDS_URL points at
# /records/list so this is normally unnecessary; it is attempted only when
# nothing was captured after the initial load.
SELECTOR_LIST_VIEW = ("button:has-text('List'), "
                      "[role='tab']:has-text('List'), "
                      "span:has-text('List')")

NAVIGATION_WAIT_UNTIL = 'domcontentloaded'

# How long to wait for the site to fetch its first flight list after a
# navigation, in milliseconds. Generous: the previous collector's failures
# were overwhelmingly slow XHRs, not missing ones.
FIRST_CAPTURE_TIMEOUT_MS = 60000

# Polling granularity while waiting for a capture.
CAPTURE_POLL_MS = 250

# How long to wait for the flight list of the next page after clicking, in
# milliseconds. Shorter than the first-capture wait: by this point the session
# is warm and the site has answered at least once.
PAGE_CAPTURE_TIMEOUT_MS = 20000

# Guard: this many consecutive clicks producing no new page ends the walk.
MAX_IDLE_CLICKS = 2


# The site rounds the period it was given (and may apply its own idea of the
# day's edges), so the returned URL is compared against the intended bounds
# with one hour of slack on each edge. One hour absorbs rounding; it is far
# too small to hide the failure this check exists for -- a period the picker
# ignored, or a range the calendar reset because it crossed a year boundary,
# is wrong by a day or more.
PERIOD_TOLERANCE_MS = 3600 * 1000

# Delay between keystrokes when typing into the date inputs. Ant Design
# revalidates on every keystroke; typing instantly has been known to leave the
# control holding a partial date.
KEY_DELAY_MS = 40


class BrowserError(Exception):
    """The browser side of the run failed."""


class SessionExpired(BrowserError):
    """The saved session no longer signs us in. main() -> exit code 2."""


class RegionMismatch(BrowserError):
    """The session is in the wrong region. main() -> exit code 7.

    [REASON]: when the account is switched to another region the flight list
    returns zero rows with no error whatsoever -- the run looks perfectly
    successful and collects nothing. This is the single most dangerous silent
    failure in the integration, and it has happened before.
    """


class PeriodVerificationFailed(BrowserError):
    """The site is not showing the period we asked for. main() -> exit code 3.

    [REASON]: a collector that silently harvests the wrong period is worse
    than one that fails -- the flights it brings back are real, they land in
    the database, and nothing downstream can tell that the window was not the
    one the operator asked for. So this is fatal and nothing is sent.
    """


# ─── Pure response filtering (unit-tested, no browser) ────────────────────────

def is_flight_list_url(url):
    """True for the flight LIST endpoint, False for detail URLs and the rest.

    Both conditions of the task are applied: the URL must be the
    flight_records LIST call (a query string, hence the '?') and must NOT
    contain '/flight_records/'.
    """
    if not url:
        return False
    if FLIGHT_LIST_URL_MARKER_LOOSE not in url:
        return False
    if FLIGHT_DETAIL_URL_MARKER in url:
        return False
    return True


def is_expected_api_version(url):
    """False when the list URL is the right endpoint on a different API version."""
    return bool(url) and FLIGHT_LIST_URL_MARKER in url


def body_code(body):
    """The in-body `code`, or None when the body is not a usable object."""
    if not isinstance(body, dict):
        return None
    value = body.get('code')
    if isinstance(value, bool):
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def is_flight_list_body(body):
    """True when the body carries data: code == 200 AND a `data` list."""
    return body_code(body) == BODY_CODE_OK and isinstance(body.get('data'), list)


def classify_response(url, body):
    """(accepted, reason) for one response.

    Reasons are stable strings, so the run summary can count them:
      'ok'                 -- captured
      'not-flight-list'    -- some other endpoint, ignored entirely
      'detail-url'         -- a single flight card, excluded by contract
      'code-101' / 'code-408' / 'code-none' -- the server rejected the request
      'no-data-list'       -- code 200 but no `data` list: not usable
    """
    if url and FLIGHT_DETAIL_URL_MARKER in url and 'flight_records' in url:
        return False, 'detail-url'
    if not is_flight_list_url(url):
        return False, 'not-flight-list'
    code = body_code(body)
    if code != BODY_CODE_OK:
        return False, 'code-%s' % ('none' if code is None else code)
    if not isinstance(body.get('data'), list):
        return False, 'no-data-list'
    return True, 'ok'


class CapturedPage(object):
    """One accepted flight-list response: the body plus the URL that asked."""

    __slots__ = ('url', 'body')

    def __init__(self, url, body):
        self.url = url
        self.body = body

    @property
    def meta(self):
        meta = self.body.get('meta_data')
        return meta if isinstance(meta, dict) else {}

    @property
    def current_page(self):
        return _as_int(self.meta.get('current_page'))

    @property
    def total_pages(self):
        return _as_int(self.meta.get('total_pages'))

    @property
    def flights(self):
        data = self.body.get('data')
        return [row for row in data if isinstance(row, dict)] if data else []

    def __repr__(self):
        return ('CapturedPage(page=%s/%s, flights=%d)'
                % (self.current_page, self.total_pages, len(self.flights)))


def _as_int(value):
    if value is None or isinstance(value, bool):
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


# ─── Period verification (unit-tested, no browser) ────────────────────────────

def parse_period_from_url(url):
    """(from_ms, to_ms) read out of a flight-list request URL.

    The parameters arrive percent-encoded as filters%5Btimestamp_gteq%5D;
    parse_qs decodes keys as well as values, so both spellings land on the
    same key. A parameter that is absent or not an integer comes back None.
    """
    if not url:
        return (None, None)
    params = parse_qs(urlsplit(url).query, keep_blank_values=True)
    return (_first_int(params.get(PARAM_PERIOD_FROM)),
            _first_int(params.get(PARAM_PERIOD_TO)))


def _first_int(values):
    if not values:
        return None
    return _as_int(values[0])


def period_matches(url, expected_from_ms, expected_to_ms,
                   tolerance_ms=PERIOD_TOLERANCE_MS):
    """True when the URL's period matches the intended one within tolerance.

    A URL carrying neither bound never matches: "no filter parameters" means
    the picker was not applied at all, which is exactly the failure this
    function exists to catch.
    """
    observed_from, observed_to = parse_period_from_url(url)
    if observed_from is None or observed_to is None:
        return False
    return (abs(observed_from - expected_from_ms) <= tolerance_ms
            and abs(observed_to - expected_to_ms) <= tolerance_ms)


def parse_page_size_option(text):
    """'50 / page' -> 50. None when the label carries no number.

    Ant Design renders the option as '<n> / page'; other locales and other
    antd versions render it differently ('50/страница', '50 条/页'), so the
    first run of digits is taken rather than the exact wording matched.
    """
    if not text:
        return None
    match = re.search(r'\d+', str(text))
    return int(match.group()) if match else None


def parse_page_size_from_url(url):
    """The page_size actually in force, read out of a request URL."""
    if not url:
        return None
    params = parse_qs(urlsplit(url).query, keep_blank_values=True)
    return _first_int(params.get('page_size'))


def dedupe_flights(flights):
    """(unique_flights, self_duplicate_count) -- deduplicated by the `id` field.

    The same page can be captured twice: a click that lands on a page the site
    re-fetches, a re-render, a retried XHR. The first occurrence of an id wins
    and the order of first appearance is preserved, so the result is
    deterministic whatever the capture order was.

    [REASON]: flights WITHOUT a usable id are passed through, never dropped.
    They cannot be deduplicated here, and the ingest endpoint will count them
    as errors and say so in its log -- which is the visible outcome. Dropping
    them in the collector would make them disappear without a trace, and a
    flight lost in the collector is unrecoverable once the DJI history window
    rolls past it.
    """
    seen = set()
    unique = []
    duplicates = 0
    for flight in flights:
        if not isinstance(flight, dict):
            continue
        flight_id = _as_int(flight.get('id'))
        if flight_id is None:
            unique.append(flight)
            continue
        if flight_id in seen:
            duplicates += 1
            continue
        seen.add(flight_id)
        unique.append(flight)
    return unique, duplicates


def count_unidentified(flights):
    """How many flights carry no numeric id (the ingest will error on these)."""
    return sum(1 for flight in flights
               if isinstance(flight, dict) and _as_int(flight.get('id')) is None)


def pages_seen(captured):
    """The set of distinct page numbers among captured pages."""
    return set(page.current_page for page in captured
               if page.current_page is not None)


def format_ms(value, tz_offset_hours):
    """'1782846000000 (2026-07-01 00:00:00 +5)' -- for log lines and errors.

    Both the raw number and its local rendering are shown: the number is what
    the site sent, the rendering is what a human can compare against the
    period they asked for.
    """
    if value is None:
        return 'absent'
    moment = (datetime(1970, 1, 1)
              + timedelta(milliseconds=value)
              + timedelta(hours=tz_offset_hours))
    sign = '+' if tz_offset_hours >= 0 else '-'
    return '%d (%s %s%g)' % (value, moment.strftime('%Y-%m-%d %H:%M:%S'),
                             sign, abs(tz_offset_hours))


# ─── The driver ───────────────────────────────────────────────────────────────

class FlightCollector(object):
    """Opens SmartFarm with a saved session and captures its flight lists.

    Usage:

        with FlightCollector(cfg) as collector:
            collector.open_records()
            ...

    Every captured page is kept with the URL that produced it, because the
    period verification reads the period back out of that URL.
    """

    def __init__(self, cfg, logger=None):
        self.cfg = cfg
        self.log = logger or log
        self._playwright = None
        self._browser = None
        self._context = None
        self._page = None
        self._captured = []
        self._rejected = {}
        self._ignored_detail = 0
        self._version_warned = False
        self._page_size_probed = False

    # -- lifecycle ------------------------------------------------------------

    def __enter__(self):
        self.start()
        return self

    def __exit__(self, *_exc):
        self.close()

    def start(self):
        """Launch Chromium with the saved session and attach the listener.

        [REASON]: the listener is attached BEFORE the first navigation. The
        site fetches its first flight list during page load; a listener
        attached after goto() misses it, and the run then either waits out its
        timeout or -- worse -- verifies the period against a URL that came
        from a later, different request.
        """
        # Lazy import: the collector's dependencies are not installed in the
        # application's Python, where the unit tests and CI import this module.
        from playwright.sync_api import sync_playwright

        from drone_collector.session import require_session

        state = require_session(self.cfg.storage_state)

        self._playwright = sync_playwright().start()
        self._browser = self._playwright.chromium.launch(
            headless=self.cfg.headless)
        self._context = self._browser.new_context(
            storage_state=str(state),
            locale='en-US',
        )
        self._page = self._context.new_page()
        self._page.set_default_timeout(self.cfg.page_timeout_ms)
        self._page.on('response', self._on_response)
        return self

    def close(self):
        for closer in (self._context, self._browser):
            try:
                if closer is not None:
                    closer.close()
            except Exception:  # pragma: no cover -- teardown must not mask errors
                pass
        try:
            if self._playwright is not None:
                self._playwright.stop()
        except Exception:  # pragma: no cover
            pass
        self._context = self._browser = self._playwright = self._page = None

    # -- capture --------------------------------------------------------------

    def _on_response(self, response):
        """Response listener. Never raises: an exception here would surface
        inside Playwright's event loop and abort the navigation."""
        try:
            url = response.url
        except Exception:  # pragma: no cover
            return
        if url and FLIGHT_DETAIL_URL_MARKER in url and 'flight_records' in url:
            self._ignored_detail += 1
            return
        if not is_flight_list_url(url):
            return
        try:
            body = response.json()
        except Exception:
            self._note_rejected('unparsable-body', url)
            return
        # [REASON]: the decision is made on the in-body `code`, never on
        # response.status -- the server answers HTTP 200 for rejections too,
        # so a status check would accept `code 101` as data.
        accepted, reason = classify_response(url, body)
        if not accepted:
            self._note_rejected(reason, url)
            return
        if not is_expected_api_version(url) and not self._version_warned:
            self._version_warned = True
            self.log.warning('The flight list is being served from a different '
                             'API path than the expected %r: %s. Captured '
                             'anyway; update the constant in browser.py.',
                             FLIGHT_LIST_URL_MARKER, url)
        page = CapturedPage(url, body)
        self._captured.append(page)
        self.log.info('Captured page %s/%s (%d flights)',
                      page.current_page, page.total_pages, len(page.flights))

    def _note_rejected(self, reason, url):
        self._rejected[reason] = self._rejected.get(reason, 0) + 1
        # The URL carries only filter parameters -- no token, no cookie, no
        # header. It is logged because the period is read out of it.
        self.log.warning('Rejected flight-list response (%s): %s', reason, url)

    @property
    def captured(self):
        return list(self._captured)

    @property
    def rejected(self):
        return dict(self._rejected)

    @property
    def ignored_detail_responses(self):
        return self._ignored_detail

    def _wait_for_capture(self, previous_count, timeout_ms):
        """Block until len(self._captured) exceeds previous_count.

        Returns True when a new page arrived. Uses the page's own wait so that
        Playwright keeps pumping its event loop -- a plain time.sleep() would
        stop the listener from ever running.
        """
        deadline = time.time() + (timeout_ms / 1000.0)
        while time.time() < deadline:
            if len(self._captured) > previous_count:
                return True
            self._page.wait_for_timeout(CAPTURE_POLL_MS)
        return len(self._captured) > previous_count

    # -- navigation -----------------------------------------------------------

    def open_records(self):
        """Navigate to the records page and wait for its first flight list."""
        self.log.info('Opening %s', self.cfg.records_url)
        self._page.goto(self.cfg.records_url,
                        wait_until=NAVIGATION_WAIT_UNTIL,
                        timeout=self.cfg.page_timeout_ms)
        self.log.info('Page URL after navigation: %s', self._page.url)

        if '/login' in (self._page.url or ''):
            raise SessionExpired(
                'the saved session at %s is no longer signed in (landed on '
                '%s) -- run `python -m drone_collector.main --save-session` '
                'again' % (self.cfg.storage_state, self._page.url))

        self.dismiss_cookie_banner()

        if not self._wait_for_capture(0, FIRST_CAPTURE_TIMEOUT_MS):
            # Map mode only fetches /flight_records/overview. One best-effort
            # attempt at the list toggle before giving up.
            self.log.warning('No flight list after %d ms, trying the List view'
                             ' toggle', FIRST_CAPTURE_TIMEOUT_MS)
            self.switch_to_list_view()
            self._wait_for_capture(0, FIRST_CAPTURE_TIMEOUT_MS)

        if not self._captured:
            if '/login' in (self._page.url or ''):
                raise SessionExpired(
                    'the saved session at %s expired during the run'
                    % self.cfg.storage_state)
            raise BrowserError(
                'the site fetched no flight list within %d ms (rejected: %s, '
                'final URL: %s)' % (FIRST_CAPTURE_TIMEOUT_MS,
                                    self._rejected or 'none', self._page.url))
        return self._captured[0]

    def dismiss_cookie_banner(self):
        """Best-effort: the banner overlays the pagination control."""
        try:
            button = self._page.locator(SELECTOR_COOKIE_ACCEPT).first
            if button.is_visible(timeout=3000):
                button.click()
                self._page.wait_for_timeout(500)
                self.log.info('Cookie banner dismissed')
        except Exception as exc:
            self.log.info('No cookie banner to dismiss (%s)', exc)

    def switch_to_list_view(self):
        """Best-effort: map mode never fetches the flight list."""
        try:
            toggle = self._page.locator(SELECTOR_LIST_VIEW).first
            toggle.click(timeout=10000)
            self._page.wait_for_timeout(self.cfg.settle_ms)
            self.log.info('Switched to the List view')
        except Exception as exc:
            self.log.info('List view toggle not used (%s)', exc)

    # -- region ---------------------------------------------------------------

    def _read_region(self):
        """The region shown on the page, or None when no indicator is found."""
        try:
            locator = self._page.locator(SELECTOR_REGION_INDICATOR)
            for index in range(min(locator.count(), 5)):
                text = (locator.nth(index).inner_text() or '').strip()
                if text:
                    return text
        except Exception as exc:
            self.log.info('Could not read the region indicator (%s)', exc)
        return None

    def check_region(self, expected):
        """Guard B: compare the region on the page against the expected one.

        Returns 'ok', 'not-found' or 'skipped'. Raises RegionMismatch when an
        indicator IS found and does not match -- a found-and-wrong element must
        block the run, while a missing one must not, because the selector is
        unverified and blocking on it would stop every run for a guess.
        """
        if not expected:
            self.log.info('DJI_EXPECTED_REGION is not set; region check '
                          'skipped')
            return 'skipped'

        observed = self._read_region()
        if observed is None:
            self.log.warning('REGION CHECK DID NOT RUN: no region indicator '
                             'matched %r on the page. Continuing -- this '
                             'selector has never been confirmed against the '
                             'live cabinet. The empty-window guard is what '
                             'protects this run.', SELECTOR_REGION_INDICATOR)
            return 'not-found'

        if expected.strip().lower() not in observed.lower():
            raise RegionMismatch(
                'the session is in the wrong region: expected something '
                'containing %r, the page shows %r. A wrong region returns an '
                'empty flight list with no error at all, so the run stops '
                'here.' % (expected, observed))

        self.log.info('Region check passed: %r contains %r', observed, expected)
        return 'ok'

    # -- period ---------------------------------------------------------------

    def _range_inputs(self):
        """The two date inputs of the Ant Design range picker, in order."""
        for selector in (SELECTOR_RANGE_INPUTS, SELECTOR_RANGE_INPUTS_FALLBACK):
            locator = self._page.locator(selector)
            try:
                count = locator.count()
            except Exception:
                count = 0
            if count >= 2:
                self.log.info('Range picker inputs found with %r', selector)
                return [locator.nth(0), locator.nth(1)]
        raise BrowserError(
            'the date range picker was not found -- looked for %r and %r under '
            '%r. Correct the selector constants at the top of browser.py.'
            % (SELECTOR_RANGE_INPUTS, SELECTOR_RANGE_INPUTS_FALLBACK,
               SELECTOR_RANGE_PICKER))

    def _type_date(self, field, text):
        """Click, select all, type YYYY-MM-DD, press Enter -- then check.

        [REASON]: on the live page both inputs carry the `readonly` attribute
        while the calendar panel is closed (verified on a saved DOM,
        2026-07-31). rc-picker drops it when the panel opens, which is why the
        click comes first -- but if the site ever sets inputReadOnly for good,
        keystrokes would land on a read-only field and change nothing, and the
        run would go on to collect the site's default period. So the value is
        read back and the failure is made loud rather than silent.
        """
        field.click(timeout=self.cfg.page_timeout_ms)
        self._page.wait_for_timeout(200)

        if self._is_readonly(field):
            self.log.warning('The date input is still read-only after the '
                             'click; typing may not take effect')

        # Select whatever the control already holds; Ant Design keeps the
        # previous value in the input and typing would otherwise append to it.
        field.press('Control+a')
        # press_sequentially replaced type() in newer Playwright; both are
        # tried so the collector is not pinned to one minor version.
        try:
            field.press_sequentially(text, delay=KEY_DELAY_MS)
        except AttributeError:  # pragma: no cover -- older Playwright
            field.type(text, delay=KEY_DELAY_MS)

        if self._input_value(field) != text:
            # fill() sets the value directly and fires the input event; it is
            # the fallback, not the default, because typing is what the
            # picker's own handlers expect.
            self.log.warning('Typing did not take on the date input, falling '
                             'back to fill()')
            try:
                field.fill(text, timeout=self.cfg.page_timeout_ms)
            except Exception as exc:
                raise BrowserError(
                    'could not set the date %s: the input rejected both typing '
                    'and fill() (%s). If the site has made the picker inputs '
                    'permanently read-only, the period has to be set by '
                    'clicking through the calendar panel instead -- see the '
                    'selector constants at the top of browser.py.' % (text, exc))

        field.press('Enter')
        self._page.wait_for_timeout(self.cfg.settle_ms)

        final = self._input_value(field)
        if final != text:
            raise BrowserError(
                'the date input holds %r after being set to %r -- the picker '
                'did not accept the value' % (final, text))

    def _is_readonly(self, field):
        try:
            return field.get_attribute('readonly') is not None
        except Exception:
            return False

    def _input_value(self, field):
        try:
            return field.input_value()
        except Exception:
            return None

    def set_period(self, date_from, date_to):
        """Type the period into the picker, then prove the site accepted it.

        The period cannot be put into the request URL: an altered query string
        fails DJI's signature check (`code 101`). It has to go through the
        site's own control, which is why it then has to be verified rather
        than assumed.

        Returns (from_ms, to_ms) -- the intended bounds, once verified.
        """
        from drone_collector.window import format_date, window_bounds_ms

        expected_from, expected_to = window_bounds_ms(
            date_from, date_to, self.cfg.tz_offset_hours)

        fields = self._range_inputs()

        # [REASON]: everything captured so far belongs to the site's DEFAULT
        # period, not to ours. Keeping it would mix flights from an unasked-for
        # window into the batch, and the run summary would still look right.
        discarded = len(self._captured)
        self._captured = []
        if discarded:
            self.log.info('Discarded %d page(s) captured before the period was '
                          'set', discarded)

        self.log.info('Setting period %s .. %s', format_date(date_from),
                      format_date(date_to))
        self._type_date(fields[0], format_date(date_from))
        self._type_date(fields[1], format_date(date_to))

        if not self._captured:
            self._wait_for_capture(0, FIRST_CAPTURE_TIMEOUT_MS)

        self.verify_period(expected_from, expected_to)
        return expected_from, expected_to

    def verify_period(self, expected_from_ms, expected_to_ms):
        """Read the period back out of the site's own request URL.

        Mandatory, and fatal when it fails: the intended and the observed
        values are both logged, PeriodVerificationFailed is raised, and the
        run sends nothing.
        """
        tz = self.cfg.tz_offset_hours
        intended = 'intended %s .. %s' % (format_ms(expected_from_ms, tz),
                                          format_ms(expected_to_ms, tz))
        if not self._captured:
            raise PeriodVerificationFailed(
                'no flight-list request was captured after the period was set '
                '(%s); rejected responses: %s'
                % (intended, self._rejected or 'none'))

        url = self._captured[-1].url
        observed_from, observed_to = parse_period_from_url(url)
        observed = 'observed %s .. %s' % (format_ms(observed_from, tz),
                                          format_ms(observed_to, tz))

        if not period_matches(url, expected_from_ms, expected_to_ms):
            self.log.error('Period verification failed: %s; %s', intended,
                           observed)
            self.log.error('Observed request URL: %s', url)
            raise PeriodVerificationFailed(
                'the site is showing a different period: %s; %s' % (intended,
                                                                    observed))

        self.log.info('Period verified: %s; %s', intended, observed)
        self._drop_captures_outside_period(expected_from_ms, expected_to_ms)
        return True

    def _drop_captures_outside_period(self, expected_from_ms, expected_to_ms):
        """Keep only pages whose own URL carries the verified period.

        [REASON]: the picker fires a request after the START date is entered,
        while the end date is still the old one. That intermediate page is a
        real, well-formed flight list for a period nobody asked for. The last
        captured URL is the one verified above; the rest are filtered here so
        that a half-applied period cannot contribute flights to the batch.
        """
        kept, dropped = [], 0
        for page in self._captured:
            if period_matches(page.url, expected_from_ms, expected_to_ms):
                kept.append(page)
            else:
                dropped += 1
        if dropped:
            self.log.info('Dropped %d page(s) captured with a half-applied '
                          'period', dropped)
        self._captured = kept
        return dropped

    def _accept_new_captures(self, before, expected_from_ms, expected_to_ms):
        """Validate the pages captured since index `before`, drop the rest."""
        fresh = self._captured[before:]
        kept = [page for page in fresh
                if period_matches(page.url, expected_from_ms, expected_to_ms)]
        dropped = len(fresh) - len(kept)
        if dropped:
            self.log.warning('Dropped %d page(s) whose URL carried a different '
                             'period', dropped)
        self._captured = self._captured[:before] + kept
        return kept

    # -- page size ------------------------------------------------------------

    def current_page_size(self):
        """The page size actually in force, from the last captured request URL.

        The URL is the authority, not the label on the control: it is what the
        API was actually asked for.
        """
        if self._captured:
            size = parse_page_size_from_url(self._captured[-1].url)
            if size:
                return size
        try:
            text = self._page.locator(SELECTOR_PAGE_SIZE_CURRENT).first.inner_text()
            return parse_page_size_option(text)
        except Exception:
            return None

    def _page_size_options(self):
        """[(size, label, locator)] from the opened dropdown, largest last."""
        for selector in (SELECTOR_PAGE_SIZE_OPTIONS,
                         SELECTOR_PAGE_SIZE_OPTIONS_FALLBACK):
            locator = self._page.locator(selector)
            try:
                count = locator.count()
            except Exception:
                count = 0
            options = []
            for index in range(count):
                item = locator.nth(index)
                try:
                    label = (item.get_attribute('title')
                             or item.inner_text() or '').strip()
                except Exception:
                    continue
                size = parse_page_size_option(label)
                if size:
                    options.append((size, label, item))
            if options:
                return sorted(options, key=lambda option: option[0])
        return []

    def maximise_page_size(self, expected_from_ms, expected_to_ms):
        """Switch the site to the largest page size it offers. Best effort.

        Returns the page size in force afterwards, or None if unknown.

        [REASON]: page_size is NOT fixed. What was proven is narrower than it
        first looked: rewriting page_size in the URL *after* the app signed the
        request is rejected with `code 101`. The value itself can change --
        the site has its own control, and when it is used the app signs a
        request carrying the new value. Observed as 30 in one session and 50
        in another, so the setting is per-session and persists.

        This never raises. A page size that cannot be changed only makes the
        run slower; aborting for it would trade a working collection for none.
        """
        before_size = self.current_page_size()
        if self._page_size_probed:
            # The setting is per-session and persists, so later windows in the
            # same run inherit it; only the value in force is worth logging.
            self.log.info('Page size in force for this window: %s', before_size)
            return before_size
        self._page_size_probed = True
        self.log.info('Page size currently in force: %s', before_size)

        try:
            changer = self._page.locator(SELECTOR_PAGE_SIZE_CHANGER).first
            if changer.count() == 0:
                self.log.warning('Page-size control %r not found; continuing at '
                                 '%s per page', SELECTOR_PAGE_SIZE_CHANGER,
                                 before_size)
                return before_size
            changer.click(timeout=self.cfg.page_timeout_ms)
            self._page.wait_for_timeout(min(self.cfg.settle_ms, 1500))

            options = self._page_size_options()
            if not options:
                self.log.warning('Page-size control opened but offered no '
                                 'readable options (%r); continuing at %s per '
                                 'page', SELECTOR_PAGE_SIZE_OPTIONS, before_size)
                self._page.keyboard.press('Escape')
                return before_size

            # Required log line: the available maximum was unknown before this
            # run, and this is how it becomes known.
            self.log.info('Page-size options offered by the site: %s',
                          [label for _size, label, _item in options])

            largest_size, largest_label, largest_item = options[-1]
            if before_size is not None and largest_size <= before_size:
                self.log.info('Already at the largest offered page size (%s)',
                              before_size)
                self._page.keyboard.press('Escape')
                return before_size

            self.log.info('Selecting the largest page size: %s', largest_label)
            captured_before = len(self._captured)
            largest_item.click(timeout=self.cfg.page_timeout_ms)
            self._wait_for_capture(captured_before, PAGE_CAPTURE_TIMEOUT_MS)
            self._page.wait_for_timeout(self.cfg.settle_ms)
            fresh = self._accept_new_captures(captured_before, expected_from_ms,
                                              expected_to_ms)
        except Exception as exc:
            self.log.warning('Could not change the page size (%s); continuing '
                             'at %s per page', exc, before_size)
            return before_size

        if not fresh:
            self.log.warning('The page-size selection produced no new request; '
                             'continuing at %s per page', before_size)
            return before_size

        effective = parse_page_size_from_url(fresh[-1].url)
        self.log.info('Page size now in force, read back from the request URL: '
                      '%s', effective)
        if effective and effective != before_size:
            # [REASON]: changing the page size renumbers the pagination -- the
            # pages captured at the old size describe a different partition of
            # the same flights, and mixing the two would make pages_seen()
            # meaningless against the new total_pages. The flights are not
            # lost: the new page 1 is a superset of the old one, and anything
            # beyond it is walked again.
            self.log.info('Pagination renumbered by the page-size change; '
                          'restarting the walk from the new first page')
            self._captured = fresh
        elif effective == before_size:
            self.log.warning('The page-size selection did not take effect; '
                             'continuing at %s per page', before_size)
        return effective or before_size

    # -- pagination -----------------------------------------------------------

    def _next_control_state(self):
        """'enabled', 'disabled' or 'missing'."""
        try:
            if self._page.locator(SELECTOR_PAGINATION_NEXT_ENABLED).count() > 0:
                return 'enabled'
            if self._page.locator(SELECTOR_PAGINATION_NEXT).count() > 0:
                return 'disabled'
        except Exception as exc:
            self.log.warning('Could not read the pagination control (%s)', exc)
        return 'missing'

    def _click_next(self):
        """Click the next-page control. True when the click was delivered.

        [REASON]: the click goes through element.click() in the page rather
        than Playwright's own click, because a consent banner or a sticky
        footer overlaying the control makes a real mouse click land on the
        overlay instead. This was the previous collector's fix and it holds.
        """
        control = self._page.locator(SELECTOR_PAGINATION_NEXT_ENABLED).first
        try:
            control.evaluate('el => el.click()')
            return True
        except Exception as exc:
            self.log.warning('JS click on the next-page control failed (%s), '
                             'trying a real click', exc)
        try:
            control.click(timeout=self.cfg.page_timeout_ms)
            return True
        except Exception as exc:
            self.log.warning('Next-page click failed (%s)', exc)
            return False

    def paginate(self, expected_from_ms, expected_to_ms):
        """Walk the remaining pages. Returns (complete, total_pages, clicks).

        Four guards, all required, any of which ends the walk:
          1. DJI_MAX_PAGES iterations, regardless of anything else;
          2. MAX_IDLE_CLICKS consecutive clicks producing no new page;
          3. current_page failing to advance;
          4. the next-page control being disabled -- a clean stop.

        `complete` is False when the walk ended before every page reported by
        meta_data.total_pages was captured. The caller decides what to do with
        that; nothing is hidden.
        """
        if not self._captured:
            raise BrowserError('paginate() called before any page was captured')

        first = self._captured[0]
        total_pages = first.total_pages or 1
        last_page = first.current_page
        self.log.info('Total pages reported by the site: %s', total_pages)

        clicks = 0
        idle_clicks = 0
        while len(pages_seen(self._captured)) < total_pages:
            # Guard 1: the hard cap, checked before anything else.
            if clicks >= self.cfg.max_pages:
                self.log.warning('Stopping: hit the DJI_MAX_PAGES cap of %d',
                                 self.cfg.max_pages)
                break

            # Guard 4: a disabled control means the site says there is no next
            # page. That is a clean stop, even if total_pages disagrees.
            state = self._next_control_state()
            if state == 'disabled':
                self.log.info('Stopping: the next-page control is disabled')
                break
            if state == 'missing':
                self.log.warning('Stopping: the next-page control was not found'
                                 ' (%r) -- correct the selector constants at the'
                                 ' top of browser.py', SELECTOR_PAGINATION_NEXT)
                break

            before = len(self._captured)
            if not self._click_next():
                break
            clicks += 1
            self._wait_for_capture(before, PAGE_CAPTURE_TIMEOUT_MS)
            self._page.wait_for_timeout(self.cfg.settle_ms)
            fresh = self._accept_new_captures(before, expected_from_ms,
                                              expected_to_ms)

            # Guard 2: nothing new arrived.
            if not fresh:
                idle_clicks += 1
                self.log.warning('Click %d produced no new page (%d in a row)',
                                 clicks, idle_clicks)
                if idle_clicks >= MAX_IDLE_CLICKS:
                    self.log.warning('Stopping: %d consecutive clicks produced '
                                     'no new page', idle_clicks)
                    break
                continue
            idle_clicks = 0

            # Guard 3: the page number did not move forward.
            numbers = [page.current_page for page in fresh
                       if page.current_page is not None]
            newest = max(numbers) if numbers else None
            if newest is None:
                self.log.warning('Stopping: the captured page carries no '
                                 'current_page')
                break
            if last_page is not None and newest <= last_page:
                self.log.warning('Stopping: current_page did not advance '
                                 '(%s -> %s)', last_page, newest)
                break
            last_page = newest

        complete = len(pages_seen(self._captured)) >= total_pages
        if not complete:
            self.log.error('Pagination incomplete: %d of %s pages captured '
                           'after %d click(s)', len(pages_seen(self._captured)),
                           total_pages, clicks)
        return complete, total_pages, clicks

    # -- the whole run --------------------------------------------------------

    def collect(self, date_from, date_to):
        """Single-window convenience: open the records page, then collect."""
        self.open_records()
        return self.collect_window(date_from, date_to)

    def collect_window(self, date_from, date_to):
        """One reporting window, on an already-open page.

        Kept separate from collect() because a period spanning a calendar-year
        boundary has to be collected one year at a time -- the picker resets a
        range that crosses the boundary -- and all those windows share one
        browser, one session and one page load.
        """
        expected_from, expected_to = self.set_period(date_from, date_to)
        page_size = self.maximise_page_size(expected_from, expected_to)
        complete, total_pages, clicks = self.paginate(expected_from,
                                                      expected_to)

        raw = []
        for page in self._captured:
            raw.extend(page.flights)
        unique, self_duplicates = dedupe_flights(raw)

        result = CollectResult(
            flights=unique,
            pages_captured=len(pages_seen(self._captured)),
            total_pages=total_pages,
            flights_captured=len(raw),
            self_duplicates=self_duplicates,
            unidentified=count_unidentified(unique),
            rejected=self.rejected,
            ignored_detail=self.ignored_detail_responses,
            clicks=clicks,
            complete=complete,
            page_size=page_size,
            date_from=date_from,
            date_to=date_to,
        )
        self.log.info('Collected %d flight(s) from %d page(s); the collector '
                      'itself removed %d duplicate(s)', len(unique),
                      result.pages_captured, self_duplicates)
        if result.unidentified:
            self.log.warning('%d captured flight(s) carry no numeric id; they '
                             'are sent anyway and the ingest will report them '
                             'as errors', result.unidentified)
        return result


class CollectResult(object):
    """What one browser run produced. Everything here goes into the summary."""

    __slots__ = ('flights', 'pages_captured', 'total_pages', 'flights_captured',
                 'self_duplicates', 'unidentified', 'rejected',
                 'ignored_detail', 'clicks', 'complete', 'page_size',
                 'date_from', 'date_to')

    def __init__(self, flights, pages_captured, total_pages, flights_captured,
                 self_duplicates, unidentified, rejected, ignored_detail,
                 clicks, complete, page_size=None, date_from=None,
                 date_to=None):
        self.flights = flights
        self.pages_captured = pages_captured
        self.total_pages = total_pages
        self.flights_captured = flights_captured
        self.self_duplicates = self_duplicates
        self.unidentified = unidentified
        self.rejected = rejected
        self.ignored_detail = ignored_detail
        self.clicks = clicks
        self.complete = complete
        self.page_size = page_size
        self.date_from = date_from
        self.date_to = date_to
