# -*- coding: utf-8 -*-
"""drone_collector/sources.py -- the immutable DJI source bodies of a flight.

    python -m drone_collector.main --sources --from 2026-08-01 --to 2026-08-31
    python -m drone_collector.main --sources --ids-file ids.txt --dry-run
    python -m drone_collector.main --sources --ids-file ids.txt --send-sources
    python -m drone_collector.main --land-snapshot [--with-geometry] [--send-snapshot]

DJI-AREA-EVIDENCE-001. Vehicle Soft keeps, per flight, the BYTES DJI served
-- not a reading of them -- so that every later figure can be re-derived
from the source instead of being believed. This module captures those bytes
and queues them for `POST /drones/api/source_sync`; a second mode snapshots
the Field Management catalog for `POST /drones/api/land_snapshot_sync`.

WHAT ONE FLIGHT VISIT CAPTURES

The collector navigates the SmartFarm SPA to `/record/<flight_id>` and
LISTENS. While the page loads, the SPA itself issues, in this order:

  card      GET  .../api/web/v1/flight_records/<id>          JSON envelope
  route     POST .../api/web/v2/flight_datas/flight_records  protobuf
  airlines  GET  .../api/web/v2/airlines/<id>                JSON with
                                                             SIGNED links
  v4        GET  .../objects/airline_v4/<id>/...?Expires=..&Signature=..
                                                             protobuf, up to
                                                             a megabyte

The airlines path has NO `flight_datas/` segment, unlike the route beside
it. That is DJI's spelling, not a typo of ours: `services/protoRequest.ts`
of the SPA reads `mixApi(`/api/web/v2/airlines/${id}`)`, and a captured
record-page trace shows the same. Assuming the symmetry cost a whole run --
see the [REASON] on `AIRLINES_PATH`.

The card, the route and the V4 file are stored byte for byte. The airlines
descriptor is NOT: its whole payload is three pre-signed storage links, each
a temporary credential. Only a derived document survives -- the envelope
code and status plus host+path of every link with the query string removed
-- and it is the ABSENCE of `file_v4_url` in it that records "DJI holds no
V4 for this flight" (`NO_V4_URL`), which is a finding in its own right.

WHY THE V4 BODY GOES THROUGH `page.route`, AND WHY THAT IS STILL LISTENING

[REASON]: the V4 body is read inside a `page.route` handler --
`resp = route.fetch(); body = resp.body(); route.fulfill(response=resp,
body=body)` -- and not from the `response` / `requestfinished` events like
the three small bodies. On the August 2026 forensic run, reading bodies of
that size from the events lost about one in four under load: Chromium had
already evicted the body when Playwright asked for it
(`Network.getResponseBody: No resource with given identifier`). With
`page.route` Playwright owns the bytes from the first one.

This does NOT breach the rule that the collector only listens. The request
is still the SPA's own: the page built it, the page's WASM signed it, and
`route.fetch()` continues THAT request with its URL, headers and signature
untouched. Nothing is altered, nothing is replayed, nothing is generated by
us, and the page receives exactly the response the storage sent. The
difference from the event path is who holds the buffer, not who asked.

WHAT NEVER ENTERS THE QUEUE

No signed link, no query string of a storage URL, no cookie, no header
value. `request_context.path` is the URL PATH -- for the V4 object,
`/api/web/v2/flight_datas/objects/airline_v4/<id>/<file>` -- with the query
cut off before the string is even built. Every body is checked for the
markers of a signed link before it is queued, and the queue checks the
serialised envelope once more.

RESUMABLE

A flight whose card, route and airlines are already in the outbox (pending
or sent), together with either its V4 or an airlines record that says there
is none, is not visited again. A re-run therefore asks DJI only for what is
still missing -- the same rule the polygon run has.
"""

import base64
import hashlib
import json
import logging
import re
import time

from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urlsplit

from drone_collector.outbox import (KIND_LAND_SNAPSHOT, KIND_SOURCE,
                                    EnvelopeTooLarge, OutboxError,
                                    SecretInEnvelope, find_secret_markers)
from drone_collector.route_ui_probe import (monotonic_ms, pump_until,
                                            read_request_ids,
                                            safe_exception_name)

log = logging.getLogger(__name__)

# Version of this mode. Travels in the diagnostics of every envelope.
SOURCES_MODE_VERSION = 'sources-1'

# Source types, spelled exactly as drones.py / dji_area.evidence spell them.
SOURCE_LIST = 'list'
SOURCE_CARD = 'card'
SOURCE_ROUTE = 'route'
SOURCE_AIRLINES = 'airlines'
SOURCE_V4 = 'v4'
SOURCE_TYPES = (SOURCE_LIST, SOURCE_CARD, SOURCE_ROUTE, SOURCE_AIRLINES,
                SOURCE_V4)
# What ONE record-page visit can yield. `list` is not among them: a list
# record comes out of the list walk, which is another mode.
VISIT_SOURCE_TYPES = (SOURCE_CARD, SOURCE_ROUTE, SOURCE_AIRLINES, SOURCE_V4)

# Schema / parser versions the receiver stores beside the body. The strings
# match tools/dji_area_import_sources.py so that a live capture and an
# imported forensic capture of the same body are the same revision.
SCHEMA_RAW_HTTP_BODY = 'raw-http-body'
SCHEMA_AIRLINES_PATHS_ONLY = 'airlines-paths-only'
V4_PARSER_VERSION = 'v4-parse-1'

# Per-flight outcome. Exactly one per visited flight.
STATUS_V4 = 'V4'                    # the V4 body was captured
STATUS_NO_V4_URL = 'NO_V4_URL'      # airlines says DJI holds no V4
STATUS_NO_V4 = 'NO_V4'              # the wait ran out
STATUS_V4_FAILED = 'V4_FAILED'      # the storage refused or the handler failed
STATUS_PAGE_ERROR = 'PAGE_ERROR'    # the record page did not open
STATUSES = (STATUS_V4, STATUS_NO_V4_URL, STATUS_NO_V4, STATUS_V4_FAILED,
            STATUS_PAGE_ERROR)

# Route identity, judged by the decoder against the flight the page asked for.
ROUTE_IDENTITY_OK = 'OK'
ROUTE_IDENTITY_MISMATCH = 'MISMATCH'
ROUTE_IDENTITY_UNDECODABLE = 'UNDECODABLE'

# Where the four sources live. Paths, never hosts: the object store answers
# on the API host today (`/api/web/v2/flight_datas/objects/airline_v4/...`)
# and the host is not ours to pin in any case. Every pattern below is
# matched against the PATH alone, and every one of them was checked against
# a captured record-page trace rather than reasoned out from its neighbour
# -- which is exactly how the airlines path went wrong.
#
# [REASON]: the card pattern is anchored on BOTH ends and demands digits.
# `/flight_records?page=..` (the list), `/flight_records/only_all_ids` and
# `/flight_records/overview` all share the prefix, and the flight list has
# already been mistaken for a card once in this package's history.
CARD_PATH = re.compile(r'^/api/web/v1/flight_records/(\d+)/?$')
ROUTE_PATH = '/api/web/v2/flight_datas/flight_records'
# [REASON]: the airlines descriptor is NOT under `flight_datas/`, although
# its two API siblings on this page are. The SPA's own source says so --
# `restRequest.get(mixApi(`/api/web/v2/airlines/${id}`))` in
# `services/protoRequest.ts` -- and a captured record-page trace of flight
# 622762394 shows exactly `GET /api/web/v2/airlines/622762394`.
# `/api/web/v2/flight_datas/airlines/<id>` was written here once, by analogy
# with the route path above, and it matched NOTHING: the run of 2026-09-09
# over the day 2026-08-18 visited 201 flights, kept 198 cards, 198 routes
# and 197 V4 bodies, and classified zero airlines. That form has never been
# served by DJI; it is not a legacy spelling and is not accepted.
AIRLINES_PATH = re.compile(r'^/api/web/v2/airlines/(\d+)/?$')
# [REASON]: diagnostics only -- NEVER a capture pattern. The defect above was
# silent: a wrong path leaves the same zero in the summary as a DJI that sent
# no descriptor, and nothing else. A path that names `airlines` but does not
# match AIRLINES_PATH is counted and named once, so that the next time the
# endpoint moves the run says what it saw instead of waiting out the ceiling
# on every flight for four hours.
AIRLINES_LIKE_PATH = re.compile(r'/airlines(?:/|$)')
# A WHOLE segment of digits in such a path is a flight id; folded away so
# that one wrong path is one entry and one warning, not one per flight. The
# segment must be whole: `v2` in `/api/web/v2/` is a version, not an id, and
# folding it would report a path nobody can look up.
_ID_SEGMENT = re.compile(r'(?<=/)\d+(?=/|$)')
# How many DISTINCT shapes are worth naming. More than a few means the guess
# is wrong, not that DJI serves a dozen airlines endpoints.
MAX_AIRLINES_LOOKALIKES = 5
V4_PATH = re.compile(r'/objects/airline_v4/(\d+)/')
# The `page.route` pattern. Matched against the whole URL by Playwright.
V4_URL_PATTERN = re.compile(r'/objects/airline_v4/')

_API_VERSION = re.compile(r'/api/web/(v\d+)/')
API_VERSION_STORAGE = 'storage-object'

# [REASON]: drones.py refuses a body above DRONE_SOURCE_MAX_BODY_BYTES (8 MiB)
# and the queue refuses an envelope above the same size -- and base64 adds a
# third. A body that cannot be delivered is counted at capture instead of
# poisoning a batch that would then never be accepted.
MAX_SOURCE_BODY_BYTES = 8 * 1024 * 1024

# Каждые столько контуров печатается строка прогресса фазы геометрии. 6171
# контуров -- это 13 строк: человек видит, что процесс жив и куда идёт, а
# лог не превращается в тысячи строк.
GEOMETRY_PROGRESS_EVERY = 500

# Сколько md5 уходит в один запрос манифеста. 6171 x 33 байта -- около 200 КБ,
# и дробить нечего; запас оставлен на рост каталога.
MANIFEST_BATCH_SIZE = 2000
MANIFEST_PATH = '/drones/api/land_geometry_manifest'


# How often the wait loop yields to Playwright while a flight loads.
SOURCE_POLL_MS = 250

# [REASON]: three record pages in a row that do not open mean the browser or
# the session is gone, not that three flights are odd. Continuing would turn
# a dead browser into a thousand PAGE_ERROR rows in a few minutes.
MAX_CONSECUTIVE_PAGE_ERRORS = 3

# The markers the RECEIVER refuses (dji_area.evidence.SECRET_MARKERS), mirrored
# so that the check happens before the body is queued rather than after the
# batch is refused. `expires=` is the one the queue's own list lacks outside
# a query string.
RECEIVER_SECRET_MARKERS = ('ossaccesskeyid=', 'signature=', 'expires=',
                           'signedurl', 'set-cookie', 'authorization:',
                           'bearer ')

# In-body code of a successful JSON envelope. NOT the HTTP status.
BODY_CODE_OK = 0

NAVIGATION_WAIT_UNTIL = 'domcontentloaded'
LOGIN_PATH = '/login'


class SourceCaptureError(Exception):
    """The source capture cannot proceed."""


# ─── Pure helpers ────────────────────────────────────────────────────────────

def utc_stamp(now=None):
    """`YYYY-MM-DD HH:MM:SS` in UTC -- the receiver's `captured_at_utc`."""
    moment = now or datetime.now(timezone.utc)
    return moment.strftime('%Y-%m-%d %H:%M:%S')


def capture_run_id(date_from=None, date_to=None, now=None):
    """`sources:<from>_<to>:<UTC stamp>`. Carries no secret."""
    moment = now or datetime.now(timezone.utc)
    stamp = moment.strftime('%Y%m%dT%H%M%SZ')
    if date_from and date_to:
        span = '%s_%s' % (date_from, date_to)
    else:
        span = 'ids-file'
    return 'sources:%s:%s' % (span, stamp)


def url_path(url):
    """The path of a URL, without scheme, host, query or fragment."""
    try:
        return urlsplit(str(url)).path or ''
    except ValueError:
        return ''


def host_and_path(url):
    """`host/path` of a URL with the query string and fragment removed.

    [REASON]: the query of a storage link IS the credential
    (`Expires`, `OSSAccessKeyId`, `Signature`). The host and the path say
    which object was named; nothing else survives.
    """
    try:
        parts = urlsplit(str(url))
    except ValueError:
        return None
    if not parts.netloc and not parts.path:
        return None
    return parts.netloc + parts.path


def api_version_of(path):
    match = _API_VERSION.search(path or '')
    if match:
        return match.group(1)
    if V4_PATH.search(path or ''):
        return API_VERSION_STORAGE
    return None


def classify_source_url(url, method='GET'):
    """(source_type, flight id named in the path) -- or (None, None)."""
    path = url_path(url)
    verb = (method or 'GET').upper()
    match = CARD_PATH.match(path)
    if match and verb == 'GET':
        return SOURCE_CARD, int(match.group(1))
    match = AIRLINES_PATH.match(path)
    if match and verb == 'GET':
        return SOURCE_AIRLINES, int(match.group(1))
    if verb == 'POST' and path.rstrip('/') == ROUTE_PATH:
        return SOURCE_ROUTE, None
    match = V4_PATH.search(path)
    if match and verb == 'GET':
        return SOURCE_V4, int(match.group(1))
    return None, None


def body_code(body):
    """In-body `code` of a JSON envelope, or None when there is none."""
    try:
        document = json.loads(bytes(body).decode('utf-8'))
    except (ValueError, UnicodeDecodeError, TypeError):
        return None
    if not isinstance(document, dict):
        return None
    code = document.get('code')
    if isinstance(code, bool) or not isinstance(code, int):
        return None
    return code


def airlines_document(body):
    """The derived airlines record, or None when the body is not its JSON.

    Keys: `code`, `status`, and `<link>_path` for `file_v4_url`,
    `std_detail_url`, `std_summary_url` -- host+path without the query, or
    None when DJI sent no link. This is the ONLY form in which the airlines
    answer is ever kept.
    """
    try:
        document = json.loads(bytes(body).decode('utf-8'))
    except (ValueError, UnicodeDecodeError, TypeError):
        return None
    if not isinstance(document, dict):
        return None
    data = document.get('data')
    airline = data.get('airline') if isinstance(data, dict) else None
    airline = airline if isinstance(airline, dict) else {}
    out = {'code': document.get('code'), 'status': document.get('status')}
    for key in ('file_v4_url', 'std_detail_url', 'std_summary_url'):
        value = airline.get(key)
        out[key + '_path'] = (host_and_path(value)
                              if isinstance(value, str) and value else None)
    return out


def airlines_bytes(document):
    """Canonical bytes of the derived record -- what is hashed and stored."""
    return json.dumps(document, ensure_ascii=False, sort_keys=True,
                      separators=(',', ':')).encode('utf-8')


def v4_url_present(document):
    return bool(document and document.get('file_v4_url_path'))


def body_secret_markers(body):
    """Markers of a signed link or credential in a raw body. Empty -- clean.

    Runs the queue's detector AND the receiver's list over the body decoded
    as text, so a body the receiver would refuse is refused here first.
    """
    text = bytes(body).decode('utf-8', errors='ignore')
    found = set(find_secret_markers(text))
    lowered = text.lower()
    for marker in RECEIVER_SECRET_MARKERS:
        if marker in lowered:
            found.add(marker.rstrip('=:'))
    return sorted(found)


def route_identity(body, expected_flight_id):
    """(status, embedded flight ids) of a route body against the visited flight.

    [REASON]: the route POST names the flight in its BODY, not in its URL,
    so the only proof that a captured route belongs to the flight whose page
    asked for it is the flight id the protobuf itself carries. A mismatch is
    still stored -- the receiver quarantines it -- but it is counted, because
    a route filed under the wrong flight is exactly the kind of quiet wrong
    number this whole track exists to prevent.
    """
    from drone_collector.route_decode import (RouteDecodeError,
                                              decode_route_response)
    try:
        decoded = decode_route_response(bytes(body))
    except RouteDecodeError:
        return ROUTE_IDENTITY_UNDECODABLE, []
    ids = [value for value in decoded.flight_ids if value is not None]
    if not ids:
        # An empty or non-OK envelope names nobody: nothing to disagree with.
        return ROUTE_IDENTITY_OK, ids
    if expected_flight_id in ids and len(set(ids)) == 1:
        return ROUTE_IDENTITY_OK, ids
    return ROUTE_IDENTITY_MISMATCH, ids


def source_item(flight_id, source_type, body, captured_at, path,
                association, api_status, run_id, parser_version=None,
                schema_version=None, extra_context=None):
    """One item of the `sources` list of /drones/api/source_sync.

    `body` is the raw bytes; `sha256` and `size_bytes` are computed from
    exactly those bytes, and the receiver recomputes both.
    """
    raw = bytes(body)
    context = {'path': path, 'association': association,
               'api_version': api_version_of(path),
               'mode_version': SOURCES_MODE_VERSION}
    if extra_context:
        context.update(extra_context)
    return {
        'flight_id': int(flight_id),
        'source_type': source_type,
        'captured_at_utc': captured_at,
        'body_b64': base64.b64encode(raw).decode('ascii'),
        'sha256': hashlib.sha256(raw).hexdigest(),
        'size_bytes': len(raw),
        'request_context': context,
        'capture_run_id': run_id,
        'parser_version': parser_version,
        'schema_version': schema_version,
        'api_status': api_status,
    }


def source_identity(flight_id, source_type):
    return '%d:%s' % (int(flight_id), source_type)


# ─── Capture state ───────────────────────────────────────────────────────────

class CapturedSource(object):
    """One body of one flight, as it came off the wire."""

    __slots__ = ('source_type', 'body', 'path', 'http_status', 'api_status',
                 'captured_at', 'method', 'association', 'extra_context')

    def __init__(self, source_type, body, path, http_status=None,
                 api_status=None, captured_at=None, method='GET',
                 association='url_path', extra_context=None):
        self.source_type = source_type
        self.body = bytes(body)
        self.path = path
        self.http_status = http_status
        self.api_status = api_status
        self.captured_at = captured_at or utc_stamp()
        self.method = method
        self.association = association
        self.extra_context = extra_context or {}

    def __repr__(self):
        return '<CapturedSource %s %d bytes>' % (self.source_type,
                                                 len(self.body or b''))


class FlightSources(object):
    """Everything one record-page visit yielded for one flight."""

    __slots__ = ('flight_id', 'items', 'status', 'v4_url_present',
                 'v4_failed', 'route_identity', 'route_embedded_ids',
                 'error_type', 'rejected', 'enqueued')

    def __init__(self, flight_id):
        self.flight_id = int(flight_id)
        self.items = {}
        self.status = None
        self.v4_url_present = None
        self.v4_failed = False
        self.route_identity = None
        self.route_embedded_ids = []
        self.error_type = None
        self.rejected = {}
        self.enqueued = set()

    def has(self, source_type):
        return source_type in self.items

    @property
    def v4_decided(self):
        """The V4 question has an answer: captured, absent at DJI, or failed."""
        return (self.has(SOURCE_V4) or self.v4_url_present is False
                or self.v4_failed)

    @property
    def settled(self):
        """Nothing more is expected from this page: stop waiting."""
        return (self.v4_decided and self.has(SOURCE_CARD)
                and self.has(SOURCE_ROUTE) and self.has(SOURCE_AIRLINES))

    @property
    def complete(self):
        """Card, route, airlines and either the V4 or DJI's word that there
        is none. `NO_V4_URL` is a complete capture; a timeout is not."""
        return (self.has(SOURCE_CARD) and self.has(SOURCE_ROUTE)
                and self.has(SOURCE_AIRLINES)
                and (self.has(SOURCE_V4) or self.v4_url_present is False))

    def outcome(self):
        if self.status == STATUS_PAGE_ERROR:
            return STATUS_PAGE_ERROR
        if self.has(SOURCE_V4):
            return STATUS_V4
        if self.v4_url_present is False:
            return STATUS_NO_V4_URL
        if self.v4_failed:
            return STATUS_V4_FAILED
        return STATUS_NO_V4

    def note_rejected(self, reason):
        self.rejected[reason] = self.rejected.get(reason, 0) + 1

    def release(self):
        """Drop the bodies once they are queued; keep the flags."""
        for item in self.items.values():
            item.body = b''

    def describe(self):
        return {'flight_id': self.flight_id, 'status': self.status,
                'sources': sorted(self.items),
                'v4_url_present': self.v4_url_present,
                'route_identity': self.route_identity,
                'rejected': dict(self.rejected),
                'error_type': self.error_type}


class SourceCapture(object):
    """The listener. Attach it to the page, then visit flights.

    Listeners never raise: an exception inside a Playwright handler surfaces
    in its event loop and aborts the navigation. Everything is counted.
    """

    def __init__(self, logger=None, max_body_bytes=MAX_SOURCE_BODY_BYTES,
                 clock=None):
        self.log = logger or log
        self.max_body_bytes = max_body_bytes
        self.clock = clock or utc_stamp
        self.flights = {}
        self.current_flight_id = None
        self.listener_errors = 0
        self.oversized = 0
        self.unattributed = 0
        self.v4_handler_errors = 0
        self.requests_failed = 0
        self.airlines_unmatched = 0
        self.airlines_unmatched_paths = []
        self.rejected = {}

    # -- lifecycle ------------------------------------------------------------

    def attach(self, page):
        """Subscribe to the page. The V4 route is registered here too."""
        page.on('requestfinished', self.note_request_finished)
        page.on('requestfailed', self.note_request_failed)
        page.route(V4_URL_PATTERN, self.handle_v4)

    def begin_flight(self, flight_id):
        flight = self.flights.get(int(flight_id))
        if flight is None:
            flight = FlightSources(flight_id)
            self.flights[flight.flight_id] = flight
        self.current_flight_id = flight.flight_id
        return flight

    def flight(self, flight_id):
        flight = self.flights.get(int(flight_id))
        if flight is None:
            flight = FlightSources(flight_id)
            self.flights[flight.flight_id] = flight
        return flight

    # -- the small bodies: card, route, airlines --------------------------------

    def note_request_finished(self, request):
        try:
            self._on_request_finished(request)
        except Exception as exc:
            self.listener_errors += 1
            self.log.warning('Source listener failed (%s); %d such failure(s)'
                             ' so far', safe_exception_name(exc),
                             self.listener_errors)

    def note_request_failed(self, request):
        try:
            source_type, _fid = classify_source_url(
                getattr(request, 'url', ''), getattr(request, 'method', 'GET'))
        except Exception:
            source_type = None
        if source_type is not None:
            self.requests_failed += 1
            self.log.warning('A %s request of the page failed before its '
                             'body arrived', source_type)

    def _on_request_finished(self, request):
        url = getattr(request, 'url', '') or ''
        method = getattr(request, 'method', 'GET') or 'GET'
        source_type, path_flight_id = classify_source_url(url, method)
        if source_type is None:
            self._note_airlines_lookalike(url_path(url))
            return
        if source_type == SOURCE_V4:
            # V4 is owned by the route handler; the event path must not
            # read the same body a second time.
            return
        response = request.response()
        if response is None:
            self._note_rejected(source_type, 'no-response')
            return
        status = getattr(response, 'status', None)
        body = response.body()
        path = url_path(url)
        self._accept(source_type, path_flight_id, body, path, status,
                     method, request)

    def _accept(self, source_type, path_flight_id, body, path, status,
                method, request=None):
        if body is None:
            self._note_rejected(source_type, 'no-body')
            return
        if len(body) > self.max_body_bytes:
            self.oversized += 1
            self._note_rejected(source_type, 'oversized')
            return

        if source_type == SOURCE_CARD:
            self._accept_card(path_flight_id, body, path, status, method)
        elif source_type == SOURCE_AIRLINES:
            self._accept_airlines(path_flight_id, body, path, status, method)
        elif source_type == SOURCE_ROUTE:
            self._accept_route(body, path, status, method, request)

    def _accept_card(self, flight_id, body, path, status, method):
        if flight_id is None:
            self.unattributed += 1
            return
        code = body_code(body)
        if status is not None and not 200 <= int(status) < 300:
            self.flight(flight_id).note_rejected('http-%s' % status)
            self._note_rejected(SOURCE_CARD, 'http-%s' % status)
            return
        if code != BODY_CODE_OK:
            # [REASON]: the decision is made on the in-body code, never on
            # the HTTP status: the API answers 200 for rejections too. A
            # `code 101` body is not the flight's card and must not become
            # a revision of it.
            self.flight(flight_id).note_rejected('code-%s' % code)
            self._note_rejected(SOURCE_CARD, 'code-%s' % code)
            return
        self._store(flight_id, CapturedSource(
            SOURCE_CARD, body, path, http_status=status, api_status=code,
            captured_at=self.clock(), method=method))

    def _accept_airlines(self, flight_id, body, path, status, method):
        if flight_id is None:
            self.unattributed += 1
            return
        # [REASON]: the same two guards the card has, and for a harder
        # reason. A refusal or a 5xx from this endpoint still answers with
        # JSON, and that JSON has no `airline.file_v4_url` -- so without the
        # guards the derived record says `file_v4_url_path: null`, which the
        # whole chain reads as DJI'S OWN WORD that no V4 exists. The visit
        # then counts as complete, the envelope carries
        # `v4_url_present=False`, and `flight_already_captured` retires the
        # flight for good: a transient error would be frozen into the
        # evidence as a finding, and no re-run could ever undo it. An error
        # body is not a descriptor and is not kept.
        code = body_code(body)
        if status is not None and not 200 <= int(status) < 300:
            self.flight(flight_id).note_rejected('http-%s' % status)
            self._note_rejected(SOURCE_AIRLINES, 'http-%s' % status)
            return
        if code != BODY_CODE_OK:
            self.flight(flight_id).note_rejected('code-%s' % code)
            self._note_rejected(SOURCE_AIRLINES, 'code-%s' % code)
            return
        document = airlines_document(body)
        if document is None:
            # The raw airlines body carries the signed links and is never
            # stored; without a readable document there is nothing to keep.
            self.flight(flight_id).note_rejected('airlines-unreadable')
            self._note_rejected(SOURCE_AIRLINES, 'unreadable')
            return
        flight = self.flight(flight_id)
        flight.v4_url_present = v4_url_present(document)
        self._store(flight_id, CapturedSource(
            SOURCE_AIRLINES, airlines_bytes(document), path,
            http_status=status,
            api_status=document.get('code')
            if isinstance(document.get('code'), int)
            and not isinstance(document.get('code'), bool) else None,
            captured_at=self.clock(), method=method,
            extra_context={'urls': 'stripped-to-host-and-path'}))

    def _accept_route(self, body, path, status, method, request):
        flight_id = self._route_flight_id(request)
        if flight_id is None:
            self.unattributed += 1
            self._note_rejected(SOURCE_ROUTE, 'unattributed')
            return
        flight = self.flight(flight_id)
        identity, embedded = route_identity(body, flight_id)
        flight.route_identity = identity
        flight.route_embedded_ids = embedded
        if identity == ROUTE_IDENTITY_MISMATCH:
            self.log.warning('Flight %d: the route body names another flight;'
                             ' stored for quarantine', flight_id)
        self._store(flight_id, CapturedSource(
            SOURCE_ROUTE, body, path, http_status=status, api_status=None,
            captured_at=self.clock(), method=method, association='page_visit',
            extra_context={'visited_flight_id': flight_id,
                           'route_identity': identity}))

    def _route_flight_id(self, request):
        """The flight the route POST asked for: its body names exactly one."""
        post_data = getattr(request, 'post_data', None) if request else None
        requested = read_request_ids(post_data)
        if requested.parsed and len(requested.ids) == 1:
            return next(iter(requested.ids))
        return self.current_flight_id

    # -- the V4 body: page.route ----------------------------------------------

    def handle_v4(self, route):
        """Continue the page's own signed request and keep the bytes.

        [REASON]: see the module docstring. `route.fetch()` performs THE
        request the page issued -- same URL, same headers, same signature;
        `route.fulfill(response=resp, body=body)` hands the page exactly what
        the storage sent. Nothing is edited on either leg.
        """
        request = getattr(route, 'request', None)
        url = getattr(request, 'url', '') or ''
        path = url_path(url)
        match = V4_PATH.search(path)
        flight_id = int(match.group(1)) if match else None
        try:
            response = route.fetch()
            body = response.body()
            status = getattr(response, 'status', None)
        except Exception as exc:
            self.v4_handler_errors += 1
            self.log.warning('The V4 fetch of flight %s failed (%s); the '
                             'request is continued without capture',
                             flight_id, safe_exception_name(exc))
            if flight_id is not None:
                self.flight(flight_id).v4_failed = True
            self._continue_quietly(route)
            return
        try:
            route.fulfill(response=response, body=body)
        except Exception as exc:
            # The page did not get its answer; the bytes are still ours.
            self.v4_handler_errors += 1
            self.log.warning('The V4 response of flight %s could not be '
                             'handed to the page (%s)', flight_id,
                             safe_exception_name(exc))
        try:
            self._accept_v4(flight_id, body, path, status)
        except Exception as exc:
            self.listener_errors += 1
            self.log.warning('The V4 body of flight %s was fetched but not '
                             'kept (%s)', flight_id, safe_exception_name(exc))

    def _continue_quietly(self, route):
        try:
            route.continue_()
        except Exception:
            pass

    def _accept_v4(self, flight_id, body, path, status):
        if flight_id is None:
            self.unattributed += 1
            self._note_rejected(SOURCE_V4, 'unattributed')
            return
        flight = self.flight(flight_id)
        if status is not None and not 200 <= int(status) < 300:
            # 403 here is almost always an expired signature.
            flight.v4_failed = True
            flight.note_rejected('http-%s' % status)
            self._note_rejected(SOURCE_V4, 'http-%s' % status)
            return
        if not body:
            flight.v4_failed = True
            self._note_rejected(SOURCE_V4, 'empty')
            return
        if len(body) > self.max_body_bytes:
            self.oversized += 1
            flight.v4_failed = True
            self._note_rejected(SOURCE_V4, 'oversized')
            return
        self._store(flight_id, CapturedSource(
            SOURCE_V4, body, path, http_status=status, api_status=None,
            captured_at=self.clock(), method='GET'))

    # -- bookkeeping ----------------------------------------------------------

    def _store(self, flight_id, item):
        flight = self.flight(flight_id)
        if item.source_type in flight.items:
            # The page fetched the same thing twice; the first answer stands.
            return
        flight.items[item.source_type] = item
        self.log.info('Flight %d: captured %s (%d bytes)', flight.flight_id,
                      item.source_type, len(item.body))

    def _note_rejected(self, source_type, reason):
        key = '%s:%s' % (source_type, reason)
        self.rejected[key] = self.rejected.get(key, 0) + 1

    def _note_airlines_lookalike(self, path):
        """An airlines-shaped path the classifier did not take. Diagnostics.

        [REASON]: see AIRLINES_LIKE_PATH. This counts, it never captures --
        a path that reaches here is by definition NOT a source, and the only
        thing it changes is that the summary can say what was seen instead
        of leaving `sources_airlines=0` to mean two different things. The
        path carries no query by construction (`url_path` cut it off), so
        naming it in the log cannot print a credential.

        [REASON]: the flight id is folded to `<id>` before the path is kept
        or said. A wrong path is wrong the same way on every flight, and
        without the folding the "distinct paths" list would grow one entry
        per flight and the warning would be repeated two hundred times --
        burying the run's own log under the very thing it is reporting.
        """
        if not path or not AIRLINES_LIKE_PATH.search(path):
            return
        self.airlines_unmatched += 1
        shape = _ID_SEGMENT.sub('<id>', path)
        if shape in self.airlines_unmatched_paths:
            return
        if len(self.airlines_unmatched_paths) >= MAX_AIRLINES_LOOKALIKES:
            return
        self.airlines_unmatched_paths.append(shape)
        self.log.warning('The page asked for %s, which names airlines but is'
                         ' not the airlines descriptor this collector knows'
                         ' (%s). No airlines record will be kept for these'
                         ' flights.', shape, AIRLINES_PATH.pattern)

    def counts(self):
        return {'listener_errors': self.listener_errors,
                'oversized': self.oversized,
                'unattributed': self.unattributed,
                'v4_handler_errors': self.v4_handler_errors,
                'requests_failed': self.requests_failed,
                'airlines_unmatched': self.airlines_unmatched,
                'airlines_unmatched_paths': list(
                    self.airlines_unmatched_paths),
                'rejected': dict(self.rejected)}


# ─── The visit ───────────────────────────────────────────────────────────────

class SourceRun(object):
    """Visit record pages one by one and wait for each to settle.

        run = SourceRun(page, capture, cfg, log)
        flight = run.capture_flight(673501214)

    `page` is the live Playwright page (or a fake in tests); the wait is
    pumped through `page.wait_for_timeout`, never `time.sleep`, so the
    listeners keep running while the page loads.
    """

    def __init__(self, page, capture, cfg, logger=None, clock=None,
                 poll_ms=SOURCE_POLL_MS):
        self.page = page
        self.capture = capture
        self.cfg = cfg
        self.log = logger or log
        self.clock = clock or monotonic_ms
        self.poll_ms = poll_ms
        self.consecutive_page_errors = 0

    def record_url(self, flight_id):
        return self.cfg.record_url_template.format(id=int(flight_id))

    def capture_flight(self, flight_id):
        from drone_collector.browser import SessionExpired

        flight = self.capture.begin_flight(flight_id)
        url = self.record_url(flight_id)
        try:
            self.page.goto(url, wait_until=NAVIGATION_WAIT_UNTIL,
                           timeout=self.cfg.page_timeout_ms)
        except Exception as exc:
            flight.status = STATUS_PAGE_ERROR
            flight.error_type = safe_exception_name(exc)
            self.consecutive_page_errors += 1
            self.log.error('Flight %d: the record page did not open (%s)',
                           flight.flight_id, flight.error_type)
            return flight

        landed = getattr(self.page, 'url', '') or ''
        if LOGIN_PATH in landed:
            raise SessionExpired(
                'the saved session is no longer signed in (landed on the '
                'login page while opening flight %d) -- run `python -m '
                'drone_collector.main --save-session` again'
                % flight.flight_id)

        self.consecutive_page_errors = 0
        settled = pump_until(self.page.wait_for_timeout, lambda: flight.settled,
                             self.clock, self.cfg.source_wait_ms, self.poll_ms)
        flight.status = flight.outcome()
        if not settled and flight.status == STATUS_NO_V4:
            self.log.warning('Flight %d: %d ms passed without a V4 body or a '
                             'word that there is none; captured so far: %s',
                             flight.flight_id, self.cfg.source_wait_ms,
                             ', '.join(sorted(flight.items)) or 'nothing')
        self.log.info('Flight %d: %s (%s)', flight.flight_id, flight.status,
                      ', '.join(sorted(flight.items)) or 'nothing captured')
        return flight

    @property
    def browser_looks_dead(self):
        return self.consecutive_page_errors >= MAX_CONSECUTIVE_PAGE_ERRORS

    def pause(self):
        if self.cfg.source_pause_ms:
            self.page.wait_for_timeout(self.cfg.source_pause_ms)


# ─── Items and the queue ─────────────────────────────────────────────────────

def source_items(flight, run_id, exclude=None):
    """The source_sync items of a flight, in a stable order."""
    skip = set(exclude or ())
    items = []
    for source_type in VISIT_SOURCE_TYPES:
        captured = flight.items.get(source_type)
        if captured is None or source_type in skip:
            continue
        parser_version = schema_version = None
        if source_type == SOURCE_CARD:
            schema_version = SCHEMA_RAW_HTTP_BODY
        elif source_type == SOURCE_AIRLINES:
            schema_version = SCHEMA_AIRLINES_PATHS_ONLY
        elif source_type == SOURCE_ROUTE:
            parser_version = _decoder_version()
        elif source_type == SOURCE_V4:
            parser_version = V4_PARSER_VERSION
        extra = dict(captured.extra_context)
        if captured.http_status is not None:
            extra['http_status'] = captured.http_status
        extra['method'] = captured.method
        items.append(source_item(
            flight.flight_id, source_type, captured.body, captured.captured_at,
            captured.path, captured.association, captured.api_status, run_id,
            parser_version=parser_version, schema_version=schema_version,
            extra_context=extra))
    return items


def _decoder_version():
    from drone_collector.route_decode import DECODER_VERSION
    return DECODER_VERSION


class EnqueueResult(object):
    __slots__ = ('queued', 'duplicates', 'too_large', 'secret_refused')

    def __init__(self):
        self.queued = 0
        self.duplicates = 0
        self.too_large = 0
        self.secret_refused = 0

    def as_dict(self):
        return {'queued': self.queued, 'duplicates': self.duplicates,
                'too_large': self.too_large,
                'secret_refused': self.secret_refused}


def enqueue_sources(outbox, items, flight=None, diagnostics=None,
                    logger=None):
    """Queue source items. Returns an EnqueueResult.

    A body carrying a marker of a signed link is refused BEFORE the queue
    sees it and counted; one above the envelope cap is counted as well. Both
    are left out rather than poisoning a batch the receiver would refuse
    whole.
    """
    out = logger or log
    result = EnqueueResult()
    for item in items:
        raw = base64.b64decode(item['body_b64'])
        markers = body_secret_markers(raw)
        if markers:
            result.secret_refused += 1
            out.error('Flight %d %s: the body carries %s; NOT queued',
                      item['flight_id'], item['source_type'],
                      ', '.join(markers))
            continue
        extra = dict(diagnostics or {})
        extra['mode_version'] = SOURCES_MODE_VERSION
        if item['source_type'] == SOURCE_AIRLINES:
            # Read back by the resumable skip: "no V4 at DJI" is a complete
            # capture and must not be asked for again.
            extra['v4_url_present'] = bool(
                v4_url_present(json.loads(raw.decode('utf-8'))))
        identity = source_identity(item['flight_id'], item['source_type'])
        try:
            _path, duplicate = outbox.enqueue(
                KIND_SOURCE, identity, item, item['sha256'],
                source='dji-record-page', diagnostics=extra)
        except EnvelopeTooLarge:
            result.too_large += 1
            out.error('Flight %d %s: %d bytes exceed the envelope cap; NOT '
                      'queued', item['flight_id'], item['source_type'],
                      item['size_bytes'])
            continue
        except SecretInEnvelope as exc:
            result.secret_refused += 1
            out.error('Flight %d %s: %s', item['flight_id'],
                      item['source_type'], exc)
            continue
        if duplicate:
            result.duplicates += 1
        else:
            result.queued += 1
        if flight is not None:
            flight.enqueued.add(item['source_type'])
    return result


# ─── Resumable skip ──────────────────────────────────────────────────────────

_KNOWN_NAME = re.compile(r'^source_(\d+)_(%s)_[0-9a-f]{16}\.json$'
                         % '|'.join(SOURCE_TYPES))


def known_sources(outbox):
    """{flight_id: {source_type: path}} from the file names of the queue.

    [REASON]: built from NAMES, not from reading every envelope. A month of
    flights is thirty thousand envelopes, and a V4 envelope is a megabyte;
    reading them to learn what is already there would take longer than the
    visits it saves.
    """
    known = {}
    try:
        paths = outbox.records(KIND_SOURCE)
    except OutboxError:
        return known
    for path in paths:
        match = _KNOWN_NAME.match(Path(path).name)
        if not match:
            continue
        known.setdefault(int(match.group(1)), {})[match.group(2)] = path
    return known


def flight_already_captured(flight_id, known, outbox):
    """True when the queue already holds everything a visit could bring."""
    types = known.get(int(flight_id)) or {}
    if not all(source_type in types
               for source_type in (SOURCE_CARD, SOURCE_ROUTE,
                                   SOURCE_AIRLINES)):
        return False
    if SOURCE_V4 in types:
        return True
    try:
        envelope = outbox.read(types[SOURCE_AIRLINES])
    except OutboxError:
        return False
    diagnostics = envelope.get('diagnostics') or {}
    return diagnostics.get('v4_url_present') is False


# ─── Dry run ─────────────────────────────────────────────────────────────────

def sources_dry_run_path(out_dir, run_id):
    safe = re.sub(r'[^A-Za-z0-9._-]+', '_', run_id)
    return Path(out_dir) / ('sources_dry_run_%s.json' % safe)


def write_sources_dry_run(items, flights, out_dir, run_id):
    """What would have been queued. Nothing is queued.

    [REASON]: the text is checked for secret markers BEFORE it is written --
    the same check the queue makes -- because a dry run is the one path by
    which a body reaches the disk without passing through the queue.
    """
    # [REASON]: the DECODED body is checked too, exactly as `enqueue_sources`
    # does before queueing. `find_secret_markers` reads the report as text,
    # and a signed link inside `body_b64` is invisible to it -- so without
    # this the dry run writes to disk precisely what a real run refuses to
    # hold, and the dry run is the path an operator reaches for when
    # something already looks wrong.
    for item in items:
        markers = body_secret_markers(base64.b64decode(item['body_b64']))
        if markers:
            raise SecretInEnvelope(
                'flight %s %s carries %s; nothing was written'
                % (item.get('flight_id'), item.get('source_type'),
                   ', '.join(markers)))
    target = sources_dry_run_path(out_dir, run_id)
    document = {
        'dry_run': True,
        'nothing_was_queued': True,
        'capture_run_id': run_id,
        'count': len(items),
        'flights': [flight.describe() for flight in flights],
        'sources': items,
    }
    text = json.dumps(document, ensure_ascii=False, indent=1)
    found = find_secret_markers(text)
    if found:
        raise SecretInEnvelope('the dry-run report carries %s; nothing was '
                               'written' % ', '.join(found))
    target.parent.mkdir(parents=True, exist_ok=True)
    with target.open('w', encoding='utf-8') as handle:
        handle.write(text)
    return target


# ─── Sending the queue ───────────────────────────────────────────────────────

class SourceDrainResult(object):
    """What became of the source queue in one sending run."""

    __slots__ = ('envelopes', 'sent', 'left_pending', 'corrupt', 'batches',
                 'counters', 'accepted', 'refusal_reasons')

    def __init__(self):
        self.envelopes = 0
        self.sent = 0
        self.left_pending = 0
        self.corrupt = 0
        self.batches = 0
        self.counters = None
        self.accepted = True
        self.refusal_reasons = []

    def as_dict(self):
        base = {'envelopes': self.envelopes, 'sent': self.sent,
                'left_pending': self.left_pending, 'corrupt': self.corrupt,
                'batches': self.batches, 'accepted': self.accepted}
        if self.counters is not None:
            base.update(self.counters.as_dict())
        return base


def source_refusal_reasons(counters, expected):
    """Why a source batch was NOT accepted in full. Empty -- accepted.

    Full acceptance is four conditions at once, none implied by HTTP 200:
    `status == "ok"`, `seen == len(batch)`, `errors == 0` and counters that
    add up. On any other answer the batch stays in `pending/` whole: the
    receiver answers with counters, not with a list, so which items landed
    cannot be known -- and re-sending is safe because a body already stored
    comes back as a duplicate, not as a second revision.
    """
    if counters is None:
        return ['the endpoint returned no counters at all']
    reasons = []
    if counters.status != 'ok':
        reasons.append('the endpoint answered status %r' % (counters.status,))
    if not counters.counters_agree:
        reasons.append('the counters do not add up: seen=%d but '
                       'new+duplicates+errors=%d'
                       % (counters.seen, counters.new + counters.duplicates
                          + counters.errors))
    if counters.errors:
        reasons.append('%d source(s) were rejected by the endpoint'
                       % counters.errors)
    if counters.seen != expected:
        reasons.append('the endpoint saw %d source(s) of the %d that were '
                       'sent' % (counters.seen, expected))
    return reasons


def _readable_pending(outbox, prefix, logger, result):
    from drone_collector.outbox import CorruptEnvelope
    readable = []
    for path in outbox.pending():
        if not path.name.startswith(prefix):
            continue
        try:
            envelope = outbox.read(path)
        except CorruptEnvelope as exc:
            outbox.quarantine(path)
            result.corrupt += 1
            logger.error('Queue entry %s is unreadable (%s); moved to '
                         'corrupt/ and left out of this run.', path.name, exc)
            continue
        readable.append((path, envelope))
    return readable


def drain_source_outbox(outbox, cfg, logger, send_fn=None):
    """POST pending source envelopes in chunks; move the accepted to `sent/`.

    Each chunk is judged on its own: an accepted chunk moves, a refused one
    stops the run and leaves itself and everything after it in `pending/`.
    Network and server errors propagate as the sender raises them, with
    nothing moved.

    [REASON]: `mark_sent` is called ONLY after the receiver accepted the
    chunk in full, and never before -- the opposite order loses bodies in
    exactly the case the on-disk queue exists for.
    """
    from drone_collector.sender import chunk_sources, send_sources

    send = send_fn or send_sources
    result = SourceDrainResult()
    readable = _readable_pending(outbox, KIND_SOURCE + '_', logger, result)
    result.envelopes = len(readable)
    if not readable:
        logger.info('The source queue holds nothing to send.')
        result.left_pending = len(outbox.pending())
        return result

    from drone_collector.sender import SourceSendResult
    total = SourceSendResult()
    chunks = chunk_sources(readable, getattr(cfg, 'source_batch_size', None))
    for index, chunk in enumerate(chunks, start=1):
        bodies = [envelope['body'] for _path, envelope in chunk]
        counters = send(bodies, cfg, logger=logger)
        result.batches += 1
        if counters is not None:
            total.add(counters.as_dict())
            total.status = counters.status
        refusals = source_refusal_reasons(counters, len(bodies))
        if refusals:
            result.accepted = False
            result.refusal_reasons = refusals
            for reason in refusals:
                logger.error('Source chunk %d/%d was NOT fully accepted: %s',
                             index, len(chunks), reason)
            logger.error('%d envelope(s) of this chunk and %d after it stay '
                         'in pending/; nothing was lost.', len(chunk),
                         sum(len(rest) for rest in chunks[index:]))
            break
        for path, _envelope in chunk:
            outbox.mark_sent(path)
            result.sent += 1
    result.counters = total
    result.left_pending = len(outbox.pending())
    return result


# ─── Catalog snapshot ────────────────────────────────────────────────────────

SNAPSHOT_MODE_VERSION = 'land-snapshot-1'

# [REASON]: the receiver caps a request at 1000 lands, and the queue caps an
# envelope at 8 MiB. A node is a kilobyte or two; a polygon in base64 is
# ten. A chunk is closed by whichever limit comes first, with room left for
# the envelope's own fields.
MAX_SNAPSHOT_CHUNK_BYTES = 6 * 1024 * 1024

SIGNED_URL_KEY = 'signedurl'


def snapshot_run_id(now=None):
    moment = now or datetime.now(timezone.utc)
    return 'lands:%s' % moment.strftime('%Y%m%dT%H%M%SZ')


def strip_signed_urls(value):
    """A deep copy with every `signedURL` key removed, at any depth.

    Case-insensitive on the key: the receiver strips the same name, and a
    DJI rename to `SignedUrl` must not slip a credential through.
    """
    if isinstance(value, dict):
        return {key: strip_signed_urls(item) for key, item in value.items()
                if not (isinstance(key, str) and key.lower() == SIGNED_URL_KEY)}
    if isinstance(value, list):
        return [strip_signed_urls(item) for item in value]
    return value


def snapshot_manifest_sha256(nodes):
    """sha256 over the sorted (uuid, contentMd5) pairs of the snapshot."""
    pairs = []
    for node in nodes:
        if not isinstance(node, dict):
            continue
        storage = ((node.get('geometry') or {}).get('storage')
                   if isinstance(node.get('geometry'), dict) else None)
        storage = storage if isinstance(storage, dict) else {}
        pairs.append([str(node.get('uuid')), storage.get('contentMd5')])
    pairs.sort(key=lambda pair: (pair[0], str(pair[1])))
    text = json.dumps(pairs, ensure_ascii=False, separators=(',', ':'))
    return hashlib.sha256(text.encode('utf-8')).hexdigest()


def _node_md5(node):
    storage = ((node.get('geometry') or {}).get('storage')
               if isinstance(node, dict) and isinstance(node.get('geometry'),
                                                        dict) else None)
    if not isinstance(storage, dict):
        return None
    value = storage.get('contentMd5')
    return str(value).lower() if value else None


def _json_size(value):
    return len(json.dumps(value, ensure_ascii=False,
                          separators=(',', ':')).encode('utf-8'))


def snapshot_chunk_bodies(run_id, captured_at, nodes, geometries=None,
                          expected_count=None, scope=None, complete=None,
                          max_nodes=None, max_bytes=MAX_SNAPSHOT_CHUNK_BYTES):
    """The request bodies of one snapshot, in order; the last is `final`.

    `geometries` is `{content_md5: body_b64}`; each polygon travels in the
    chunk of the first node that names its md5. Nodes must already be
    stripped of signed links.
    """
    from drone_collector.config import MAX_LAND_SNAPSHOT_BATCH_SIZE
    cap = min(int(max_nodes or MAX_LAND_SNAPSHOT_BATCH_SIZE),
              MAX_LAND_SNAPSHOT_BATCH_SIZE)
    if cap < 1:
        cap = 1
    geometries = dict(geometries or {})
    placed = set()

    chunks = []
    current, current_geoms, current_bytes = [], [], 0
    for node in nodes:
        md5 = _node_md5(node)
        geometry = None
        if md5 and md5 in geometries and md5 not in placed:
            geometry = {'content_md5': md5, 'body_b64': geometries[md5]}
        size = _json_size(node) + (_json_size(geometry) if geometry else 0)
        if current and (len(current) >= cap
                        or current_bytes + size > max_bytes):
            chunks.append((current, current_geoms))
            current, current_geoms, current_bytes = [], [], 0
        current.append(node)
        current_bytes += size
        if geometry:
            current_geoms.append(geometry)
            placed.add(md5)
    if current or not chunks:
        chunks.append((current, current_geoms))

    bodies = []
    total = len(chunks)
    for index, (chunk_nodes, chunk_geoms) in enumerate(chunks, start=1):
        final = index == total
        snapshot = {
            'capture_run_id': run_id,
            'captured_at_utc': captured_at,
            'expected_count': expected_count,
            'scope': dict(scope or {}),
            'chunk': index,
            'chunks': total,
            'final': final,
            'complete': (bool(complete) if complete is not None else None)
            if final else None,
            'manifest_sha256': snapshot_manifest_sha256(nodes)
            if final else None,
        }
        bodies.append({'snapshot': snapshot, 'lands': chunk_nodes,
                       'geometries': chunk_geoms})
    return bodies


def snapshot_body_sha256(body):
    text = json.dumps(body, ensure_ascii=False, sort_keys=True,
                      separators=(',', ':'))
    return hashlib.sha256(text.encode('utf-8')).hexdigest()


def snapshot_identity(run_id, index):
    return '%s:%04d' % (run_id, int(index))


def enqueue_snapshot_chunks(outbox, bodies, diagnostics=None, logger=None):
    """Queue the chunks of one snapshot. Returns an EnqueueResult."""
    out = logger or log
    result = EnqueueResult()
    for body in bodies:
        snapshot = body.get('snapshot') or {}
        identity = snapshot_identity(snapshot.get('capture_run_id'),
                                     snapshot.get('chunk') or 0)
        extra = dict(diagnostics or {})
        extra['mode_version'] = SNAPSHOT_MODE_VERSION
        extra['lands'] = len(body.get('lands') or [])
        extra['geometries'] = len(body.get('geometries') or [])
        try:
            _path, duplicate = outbox.enqueue(
                KIND_LAND_SNAPSHOT, identity, body, snapshot_body_sha256(body),
                source='dji-field-management', diagnostics=extra)
        except EnvelopeTooLarge:
            result.too_large += 1
            out.error('Snapshot chunk %s exceeds the envelope cap; NOT queued',
                      identity)
            continue
        except SecretInEnvelope as exc:
            result.secret_refused += 1
            out.error('Snapshot chunk %s: %s', identity, exc)
            continue
        if duplicate:
            result.duplicates += 1
        else:
            result.queued += 1
    return result


class GeometryDownloadCounters(object):
    __slots__ = ('selected', 'downloaded', 'no_geometry', 'failed',
                 'md5_mismatch', 'too_large', 'secret_in_payload', 'bytes',
                 # Уже лежит в неизменяемом хранилище приёмника -- пропущено
                 # ДО скачивания. Отдельно от `no_geometry` (у контура вообще
                 # нет полигона) и от внутрирунного дубля.
                 'known_skipped', 'duplicate_in_run')

    def __init__(self):
        for key in self.__slots__:
            setattr(self, key, 0)

    def as_dict(self):
        return {key: getattr(self, key) for key in self.__slots__}


def download_snapshot_geometries(nodes, download_fn, logger=None,
                                 sleep_fn=None, pause_s=0.35,
                                 max_bytes=MAX_SOURCE_BODY_BYTES,
                                 known_md5=None,
                                 progress_every=GEOMETRY_PROGRESS_EVERY):
    """{content_md5: body_b64} of the polygons of the given nodes.

    The bytes are kept VERBATIM -- the receiver stores them by md5 -- after
    the same three checks the polygon run makes: the download arrived, its
    md5 is the one DJI named, and it carries no signed link. The signed link
    is taken from the node once and cleared at once.

    `known_md5` is the set of `contentMd5` the receiver ALREADY stores. A
    contour whose md5 is in it is skipped BEFORE the download -- that is the
    whole point of the incremental run, and the test asserts it by checking
    that the link was never requested, not merely that the body was dropped.

    [REASON]: the md5 comes from the CATALOG node (`geometry.storage.
    contentMd5`), not from the downloaded bytes, so the decision is available
    before a single byte is fetched. Were it otherwise no incremental run
    would be possible at all.

    [REASON]: `known_md5=None` means "we could not find out" and downloads
    everything, exactly as before. An unreachable manifest must degrade to a
    slow-but-correct run, never to a snapshot with silently missing polygons.
    """
    from drone_collector.geometry import contour_from_node, scrub

    out = logger or log
    sleep = sleep_fn or time.sleep
    counters = GeometryDownloadCounters()
    known = frozenset(str(m).lower() for m in (known_md5 or ()))
    geometries = {}
    sources = [source for source in (contour_from_node(node) for node in nodes)
               if source is not None]
    counters.selected = len(sources)
    for index, source in enumerate(sources, start=1):
        if progress_every and index % progress_every == 0:
            out.info('Geometry %d/%d: known=%d new=%d failed=%d',
                     index, len(sources), counters.known_skipped,
                     counters.downloaded, _geometry_failures(counters))
        if not source.has_link or not source.content_md5:
            counters.no_geometry += 1
            continue
        md5 = str(source.content_md5).lower()
        if md5 in known:
            # Ссылка всё равно снимается: подписанный URL не должен пережить
            # этот цикл ни в узле, ни в памяти.
            source.take_link()
            counters.known_skipped += 1
            continue
        if md5 in geometries:
            source.take_link()
            counters.duplicate_in_run += 1
            continue
        link = source.take_link()
        try:
            blob = download_fn(link)
        except Exception as exc:
            counters.failed += 1
            out.warning('Contour %s did not download (%s)', source.uuid,
                        scrub(exc))
            continue
        finally:
            link = None
        if not isinstance(blob, (bytes, bytearray)) or not blob:
            counters.failed += 1
            out.warning('Contour %s: the download returned an empty body',
                        source.uuid)
            continue
        blob = bytes(blob)
        if len(blob) > max_bytes:
            counters.too_large += 1
            out.warning('Contour %s: %d bytes exceed the cap', source.uuid,
                        len(blob))
            continue
        if hashlib.md5(blob).hexdigest().lower() != md5:
            # [REASON]: a differing md5 is another object or a cut body; a
            # polygon of the wrong field stored under this md5 would be a
            # confident wrong area later.
            counters.md5_mismatch += 1
            out.warning('Contour %s: DJI named a different content md5; '
                        'not kept', source.uuid)
            continue
        if find_secret_markers(blob.decode('utf-8', errors='replace')):
            counters.secret_in_payload += 1
            out.warning('Contour %s: the payload carries a secret marker; '
                        'not kept', source.uuid)
            continue
        counters.downloaded += 1
        counters.bytes += len(blob)
        geometries[md5] = base64.b64encode(blob).decode('ascii')
        if index < len(sources) and pause_s:
            sleep(pause_s)
    out.info('Geometry %d/%d done: known=%d new=%d no-polygon=%d failed=%d',
             len(sources), len(sources), counters.known_skipped,
             counters.downloaded, counters.no_geometry,
             _geometry_failures(counters))
    return geometries, counters


def _geometry_failures(counters):
    """Всё, что НЕ доехало: отказ, чужой md5, перебор размера, секрет."""
    return (counters.failed + counters.md5_mismatch + counters.too_large
            + counters.secret_in_payload)


def snapshot_dry_run_path(out_dir, run_id):
    safe = re.sub(r'[^A-Za-z0-9._-]+', '_', run_id)
    return Path(out_dir) / ('land_snapshot_dry_run_%s.json' % safe)


def write_snapshot_dry_run(bodies, out_dir, run_id):
    """What would have been queued. Checked for secrets before writing."""
    target = snapshot_dry_run_path(out_dir, run_id)
    document = {'dry_run': True, 'nothing_was_queued': True,
                'capture_run_id': run_id, 'chunks': bodies}
    text = json.dumps(document, ensure_ascii=False, indent=1)
    found = find_secret_markers(text)
    if found:
        raise SecretInEnvelope('the dry-run report carries %s; nothing was '
                               'written' % ', '.join(found))
    target.parent.mkdir(parents=True, exist_ok=True)
    with target.open('w', encoding='utf-8') as handle:
        handle.write(text)
    return target


class SnapshotDrainResult(SourceDrainResult):
    """Same shape as the source drain; counters are a LandSnapshotSendResult."""


def snapshot_refusal_reasons(counters, expected_lands, expected_geometries):
    """Why a snapshot chunk was NOT accepted in full. Empty -- accepted."""
    if counters is None:
        return ['the endpoint returned no counters at all']
    reasons = []
    if counters.status != 'ok':
        reasons.append('the endpoint answered status %r' % (counters.status,))
    if not counters.counters_agree:
        reasons.append('the counters do not add up')
    if counters.errors:
        reasons.append('%d land(s) were rejected by the endpoint'
                       % counters.errors)
    if counters.geometries_errors:
        reasons.append('%d geometry(ies) were rejected by the endpoint'
                       % counters.geometries_errors)
    if counters.lands_seen != expected_lands:
        reasons.append('the endpoint saw %d land(s) of the %d that were sent'
                       % (counters.lands_seen, expected_lands))
    if counters.geometries_seen != expected_geometries:
        reasons.append('the endpoint saw %d geometry(ies) of the %d that were '
                       'sent' % (counters.geometries_seen,
                                 expected_geometries))
    return reasons


def drain_land_snapshot_outbox(outbox, cfg, logger, send_fn=None):
    """POST pending snapshot chunks in order; move the accepted to `sent/`.

    Order is by identity -- `<run_id>:<chunk>` -- so an older, unsent
    snapshot goes before a newer one and the `final` chunk of each goes
    last. A refused chunk stops the run with everything after it pending.
    """
    from drone_collector.sender import (LandSnapshotSendResult,
                                        send_land_snapshot_chunk)

    send = send_fn or send_land_snapshot_chunk
    result = SnapshotDrainResult()
    readable = _readable_pending(outbox, KIND_LAND_SNAPSHOT + '_', logger,
                                 result)
    readable.sort(key=lambda pair: str(pair[1].get('identity')))
    result.envelopes = len(readable)
    if not readable:
        logger.info('The snapshot queue holds nothing to send.')
        result.left_pending = len(outbox.pending())
        return result

    total = LandSnapshotSendResult()
    for index, (path, envelope) in enumerate(readable, start=1):
        body = envelope['body']
        counters = send(body, cfg, logger=logger, index=index,
                        total=len(readable))
        result.batches += 1
        if counters is not None:
            total.add(counters.as_dict())
            total.status = counters.status
        refusals = snapshot_refusal_reasons(
            counters, len(body.get('lands') or []),
            len(body.get('geometries') or []))
        if refusals:
            result.accepted = False
            result.refusal_reasons = refusals
            for reason in refusals:
                logger.error('Snapshot chunk %d/%d was NOT fully accepted: '
                             '%s', index, len(readable), reason)
            logger.error('This chunk and %d after it stay in pending/; '
                         'nothing was lost.', len(readable) - index)
            break
        outbox.mark_sent(path)
        result.sent += 1
    result.counters = total
    result.left_pending = len(outbox.pending())
    return result


# ─── DRONE-AREA-CAPTURE-001 / A13: неизменяемый источник СПИСКА ──────────────
#
# Долг A13: поля списка (площадь, ширина, режим, границы окна) приходили в
# расчёт из ИЗМЕНЯЕМОЙ колонки `drone_flights.raw_json`. Её можно переписать
# позже -- значит цепочка доказательств рвалась в первом же звене.
#
# Что кладётся в ревизию: БАЙТЫ СТРАНИЦЫ, как их прислал DJI, без
# пересериализации. Одна страница даёт по одной ревизии на каждый вылет в
# ней, и все они ссылаются на одно и то же тело.
#
# [REASON]: почему не одна ревизия на страницу. `dji_source_revisions`
# адресуется парой (source_type, scope_key) со scope_key = flight_id, и
# `latest_revisions(flight_id)` -- то, чем `dji_area/store.py` уже собирает
# `dji_flight_evidence`. Ревизия с flight_id=NULL туда не попадёт, и
# пришлось бы заводить таблицу связей, менять приёмник и менять резолвер
# ради того же результата. Тело на диске адресуется по sha256 и НЕ
# дублируется (`store.write_body_file`), так что цена схемы -- строки, а не
# байты.
#
# [REASON]: почему не «вырезать запись одного вылета и сохранить её». Так
# делает форензик-импорт (`schema_version='list-record-canonical-json'`), и
# для архива это единственный доступный вариант. Но у живого захвата есть
# настоящий ответ DJI, и хеш от нашего среза не проверить ничем: срез сделан
# нами. Поэтому живой захват хранит страницу целиком, а нужную запись
# выбирает читатель -- детерминированно и на виду.


def list_scope_context(url, page_number, total_pages, window_from, window_to,
                       flight_count, page_sha256):
    """`request_context` ревизии списка. Только пути и счётчики, без query."""
    return {
        'path': url_path(url),
        'association': 'list_page',
        'api_version': api_version_of(url_path(url)),
        'mode_version': SOURCES_MODE_VERSION,
        'list_page': page_number,
        'list_total_pages': total_pages,
        'list_window_from': window_from,
        'list_window_to': window_to,
        'list_flight_count': flight_count,
        # Тот же хеш, что и `sha256` ревизии: страница у всех её вылетов
        # одна, и по этому полю видно, что они пришли из одного ответа.
        'list_page_sha256': page_sha256,
    }


def list_source_items(pages, run_id, captured_at, window_from=None,
                      window_to=None, parser_version=None):
    """Элементы `sources` для /drones/api/source_sync из страниц списка.

    `pages` -- последовательность объектов с `url`, `raw` (bytes или None) и
    `body` (разобранный ответ). Страница без сырых байтов пропускается: без
    них ревизия была бы хешем нашей сериализации, а не ответа DJI.

    Возвращает (items, stats).
    """
    items = []
    stats = {'pages': 0, 'pages_without_raw': 0, 'flights': 0,
             'flights_without_id': 0}
    for page in pages:
        raw = getattr(page, 'raw', None)
        if not raw:
            stats['pages_without_raw'] += 1
            continue
        raw = bytes(raw)
        stats['pages'] += 1
        sha = hashlib.sha256(raw).hexdigest()
        body = getattr(page, 'body', None) or {}
        meta = body.get('meta_data') if isinstance(body, dict) else None
        meta = meta if isinstance(meta, dict) else {}
        rows = body.get('data') if isinstance(body, dict) else None
        rows = [row for row in rows if isinstance(row, dict)] if rows else []
        context = list_scope_context(
            page.url, meta.get('current_page'), meta.get('total_pages'),
            window_from, window_to, len(rows), sha)
        for row in rows:
            flight_id = row.get('id')
            if not isinstance(flight_id, int):
                stats['flights_without_id'] += 1
                continue
            items.append(source_item(
                # [REASON]: `body_code` ждёт БАЙТЫ. Первая редакция давала
                # ему разобранный dict: `bytes(dict)` бросает TypeError,
                # который функция гасит, и `api_status` у КАЖДОЙ живой
                # ревизии списка молча оставался NULL -- те же байты из
                # форензик-импорта при этом получали 0, и одно и то же тело
                # описывалось по-разному в зависимости от того, кто успел
                # первым.
                flight_id, SOURCE_LIST, raw, captured_at,
                url_path(page.url), 'list_page', body_code(raw), run_id,
                parser_version=parser_version,
                schema_version=SCHEMA_RAW_HTTP_BODY,
                extra_context=context))
            stats['flights'] += 1
    return items, stats
